## Import Packages

In [2]:
import xarray as xr
import pandas as pd
import numpy as np
import holoviews as hv
from holoviews import opts
import dask.dataframe as dd
import hvplot.dask  # noqa

import numpy as np
import holoviews as hv
import pandas as pd
import numpy as np

import polars as pl

hv.extension('bokeh')

# Import Data

In [2]:
# 25 MB chunks 

df15 = dd.read_csv('ssp126_projectedstatus_usa_offshore_daily_2015_2020.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df21 = dd.read_csv('ssp126_projectedstatus_usa_offshore_daily_2021_2030.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df31 = dd.read_csv('ssp126_projectedstatus_usa_offshore_daily_2031_2040.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df41 = dd.read_csv('ssp126_projectedstatus_usa_offshore_daily_2041_2050.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df51 = dd.read_csv('ssp126_projectedstatus_usa_offshore_daily_2051_2060.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df61 = dd.read_csv('ssp126_projectedstatus_usa_offshore_daily_2061_2070.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df71 = dd.read_csv('ssp126_projectedstatus_usa_offshore_daily_2071_2080.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df81 = dd.read_csv('ssp126_projectedstatus_usa_offshore_daily_2081_2090.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df91 = dd.read_csv('ssp126_projectedstatus_usa_offshore_daily_2091_2100.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})

In [3]:
# merge dask dataframe to pandas dataframe
import dask.dataframe as dd
join = dd.concat([df15, df21])
join2 = dd.concat([join, df31])
join3 = dd.concat([join2, df41])
join4 = dd.concat([join3, df51])
join5 = dd.concat([join4, df61])
join6 = dd.concat([join5, df71])
join7 = dd.concat([join6, df81])
SSP126 = dd.concat([join7, df91])

# inspect results
# join.compute()

In [4]:
SSP126.tail()

,index,time,lat,lon,sfcwind,Capacity (MW),City,"Local area (taluk, county)","Major area (prefecture, district)",State/Province,Region,Country,sfc_wind80m,sfc_wind80m_floor
142423,23111,2100-12-27,33.75,-78.25,2.060126,627.0,Oak Island,<NA>,<NA>,North Carolina,Americas,United States,2.773548,2.5
142424,23111,2100-12-28,33.75,-78.25,4.236203,627.0,Oak Island,<NA>,<NA>,North Carolina,Americas,United States,5.703200,5.5
142425,23111,2100-12-29,33.75,-78.25,5.846201,627.0,Oak Island,<NA>,<NA>,North Carolina,Americas,United States,7.870740,7.5
142426,23111,2100-12-30,33.75,-78.25,7.400647,627.0,Oak Island,<NA>,<NA>,North Carolina,Americas,United States,9.963492,9.5
142427,23111,2100-12-31,33.75,-78.25,8.711453,627.0,Oak Island,<NA>,<NA>,North Carolina,Americas,United States,11.728230,11.5

In [5]:
SSP126.head()

,index,time,lat,lon,sfcwind,Capacity (MW),City,"Local area (taluk, county)","Major area (prefecture, district)",State/Province,Region,Country,sfc_wind80m,sfc_wind80m_floor
0,21562,2015-01-01,39.25,-73.75,10.625036,1510.0,Atlantic City,<NA>,<NA>,New Jersey,Americas,United States,14.304487,14.0
1,21562,2015-01-02,39.25,-73.75,9.375778,1510.0,Atlantic City,<NA>,<NA>,New Jersey,Americas,United States,12.622611,12.5
2,21562,2015-01-03,39.25,-73.75,6.137069,1510.0,Atlantic City,<NA>,<NA>,New Jersey,Americas,United States,8.262337,8.0
3,21562,2015-01-04,39.25,-73.75,6.739916,1510.0,Atlantic City,<NA>,<NA>,New Jersey,Americas,United States,9.073950,9.0
4,21562,2015-01-05,39.25,-73.75,8.769224,1510.0,Atlantic City,<NA>,<NA>,New Jersey,Americas,United States,11.806007,11.5

In [6]:
SSP126['Year'] = SSP126['time'].astype(str).str[:4] # creating year column
SSP126['Year'] = SSP126['Year'].astype(int) 
# add a column that is called 'loc' and it is the combination of lat and lon with a comma in between
SSP126['loc'] = SSP126['lat'].astype(str) + ',' + SSP126['lon'].astype(str)


SSP126.head()

,index,time,lat,lon,sfcwind,Capacity (MW),City,"Local area (taluk, county)","Major area (prefecture, district)",State/Province,Region,Country,sfc_wind80m,sfc_wind80m_floor,Year,loc
0,21562,2015-01-01,39.25,-73.75,10.625036,1510.0,Atlantic City,<NA>,<NA>,New Jersey,Americas,United States,14.304487,14.0,2015,"39.25,-73.75"
1,21562,2015-01-02,39.25,-73.75,9.375778,1510.0,Atlantic City,<NA>,<NA>,New Jersey,Americas,United States,12.622611,12.5,2015,"39.25,-73.75"
2,21562,2015-01-03,39.25,-73.75,6.137069,1510.0,Atlantic City,<NA>,<NA>,New Jersey,Americas,United States,8.262337,8.0,2015,"39.25,-73.75"
3,21562,2015-01-04,39.25,-73.75,6.739916,1510.0,Atlantic City,<NA>,<NA>,New Jersey,Americas,United States,9.073950,9.0,2015,"39.25,-73.75"
4,21562,2015-01-05,39.25,-73.75,8.769224,1510.0,Atlantic City,<NA>,<NA>,New Jersey,Americas,United States,11.806007,11.5,2015,"39.25,-73.75"

In [7]:
# split the 'SSP126' into datasets with the following years: 2015-2039, 2040-2064, 2065-2089, 2090-2100
SSP126_2015_2039 = SSP126[SSP126['Year'] <= 2039]
SSP126_2040_2064 = SSP126[(SSP126['Year'] >= 2040) & (SSP126['Year'] <= 2064)]
SSP126_2065_2089 = SSP126[(SSP126['Year'] >= 2065) & (SSP126['Year'] <= 2089)]
SSP126_2090_2100 = SSP126[SSP126['Year'] >= 2090]

Apply IEC Class

In [8]:
#group by loc and find the mean sfc_wind80m_floor. Uncomment and run one at a time. this takes a long time


SSP126_2015_2039_iec = SSP126_2015_2039.groupby('loc')['sfc_wind80m_floor'].mean().compute()
SSP126_2040_2064_iec = SSP126_2040_2064.groupby('loc')['sfc_wind80m_floor'].mean().compute()
SSP126_2065_2089_iec = SSP126_2065_2089.groupby('loc')['sfc_wind80m_floor'].mean().compute()
SSP126_2090_2100_iec = SSP126_2090_2100.groupby('loc')['sfc_wind80m_floor'].mean().compute()

In [9]:
def IEC_Class(s): # s being sfc_wind80m_foor  25-year avg 
    if s < 7.5:
        return 1
    elif  7.5 <= s <= 8.5:
        return 2
    elif s > 8.5:
        return 3

In [10]:
#apply the IEC_Class function to the mean sfc_wind80m_floor in SSP126_2015_2039_iec and name the column 'iec'. Uncomment and run one at a time

SSP126_2015_2039_iec_n = SSP126_2015_2039_iec.apply(IEC_Class).rename('iec')
SSP126_2040_2064_iec_n = SSP126_2040_2064_iec.apply(IEC_Class).rename('iec')
SSP126_2065_2089_iec_n = SSP126_2065_2089_iec.apply(IEC_Class).rename('iec')
SSP126_2090_2100_iec_n = SSP126_2090_2100_iec.apply(IEC_Class).rename('iec')

In [11]:
# merge the two dataframes on loc. Uncomment and run one at a time
 
SSP126_2015_2039 = dd.merge(SSP126_2015_2039, SSP126_2015_2039_iec_n, on='loc', how='left')
SSP126_2040_2064 = dd.merge(SSP126_2040_2064, SSP126_2040_2064_iec_n, on='loc', how='left')
SSP126_2065_2089 = dd.merge(SSP126_2065_2089, SSP126_2065_2089_iec_n, on='loc', how='left')
SSP126_2090_2100 = dd.merge(SSP126_2090_2100, SSP126_2090_2100_iec_n, on='loc', how='left')

In [12]:
#rename 'sfc_wind80m_floor_x' to 'sfc_wind80m_floor'. Uncomment and run one at a time
SSP126_2015_2039 = SSP126_2015_2039.rename(columns={'sfc_wind80m_floor_x': 'sfc_wind80m_floor'})
SSP126_2040_2064 = SSP126_2040_2064.rename(columns={'sfc_wind80m_floor_x': 'sfc_wind80m_floor'})
SSP126_2065_2089 = SSP126_2065_2089.rename(columns={'sfc_wind80m_floor_x': 'sfc_wind80m_floor'})
SSP126_2090_2100 = SSP126_2090_2100.rename(columns={'sfc_wind80m_floor_x': 'sfc_wind80m_floor'})

In [13]:
IEC_Classifications = dd.read_csv('iec_classifications.csv')
# convert IEC_Class to i64
IEC_Classifications.compute()

     iec  CP_whole  sfc_wind80m_floor  Unnamed: 3        CP
0      1   19.3936                3.0         NaN  0.193936
1      1   33.1932                3.5         NaN  0.331932
2      1   37.9232                4.0         NaN  0.379232
3      1   41.4574                4.5         NaN  0.414574
4      1   42.1845                5.0         NaN  0.421845
..   ...       ...                ...         ...       ...
130    3    1.8872               23.0         NaN  0.018872
131    3    1.6623               23.5         NaN  0.016623
132    3    1.4601               24.0         NaN  0.014601
133    3    1.2781               24.5         NaN  0.012781
134    3    1.1140               25.0         NaN  0.011140

[135 rows x 5 columns]

Now we apply the Capacity Factors to each unique IEC Class

In [14]:
# merge the data on 'iec' and 'sfc_wind80m'. Uncomment and run one at a time
SSP126_2015_2039_n = dd.merge(SSP126_2015_2039, IEC_Classifications, on=['iec', 'sfc_wind80m_floor'], how='left')
SSP126_2040_2064_n = dd.merge(SSP126_2040_2064, IEC_Classifications, on=['iec', 'sfc_wind80m_floor'], how='left')
SSP126_2065_2089_n = dd.merge(SSP126_2065_2089, IEC_Classifications, on=['iec', 'sfc_wind80m_floor'], how='left')
SSP126_2090_2100_n = dd.merge(SSP126_2090_2100, IEC_Classifications, on=['iec', 'sfc_wind80m_floor'], how='left')

In [15]:
# average the CP by TEMELE_REGIONS_COPY and time. Uncomment and run one at a time. this takes a long time
SSP126_2015_2039_tt = SSP126_2015_2039_n.groupby(['State/Province', 'time'])['CP', 'Capacity (MW)'].mean().compute()
SSP126_2040_2064_tt = SSP126_2040_2064_n.groupby(['State/Province', 'time'])['CP', 'Capacity (MW)'].mean().compute()
SSP126_2065_2089_tt = SSP126_2065_2089_n.groupby(['State/Province', 'time'])['CP', 'Capacity (MW)'].mean().compute()
SSP126_2090_2100_tt = SSP126_2090_2100_n.groupby(['State/Province', 'time'])['CP', 'Capacity (MW)'].mean().compute()

In [16]:
SSP126_2015_2039_tt.head()

                                 CP  Capacity (MW)
State/Province time
California     2015-01-01  0.392065          880.0
               2015-01-02  0.368036          880.0
               2015-01-03  0.302823          880.0
               2015-01-04  0.329508          880.0
               2015-01-05  0.424942          880.0

In [17]:
#save to csv. Uncomment and run one at a time

SSP126_2015_2039_tt.to_csv('SSP126_projectedstatus_usa_offshore_2015_2039_test_state.csv')
SSP126_2040_2064_tt.to_csv('SSP126_projectedstatus_usa_offshore_2040_2064_test_state.csv')
SSP126_2065_2089_tt.to_csv('SSP126_projectedstatus_usa_offshore_2065_2089_test_state.csv')
SSP126_2090_2100_tt.to_csv('SSP126_projectedstatus_usa_offshore_2090_2100_test_state.csv')

Organize in the Format that is compliant with TIMES/VEDA 2.0 --> Only Run the Block associated with the proper SSP

In [3]:
# dask open csv
SSP126_2015_2039_tt = dd.read_csv('SSP126_projectedstatus_usa_onshore_2015_2039_test_state.csv')
SSP126_2040_2064_tt = dd.read_csv('SSP126_projectedstatus_usa_onshore_2040_2064_test_state.csv')
SSP126_2065_2089_tt = dd.read_csv('SSP126_projectedstatus_usa_onshore_2065_2089_test_state.csv')
SSP126_2090_2100_tt = dd.read_csv('SSP126_projectedstatus_usa_onshore_2090_2100_test_state.csv')

# 2015-2039

In [4]:
#   SSP 126 2015-2039
#create a new column called 'Month' that is the month of the 'time' column
SSP126_2015_2039_tt['Month'] = SSP126_2015_2039_tt['time'].astype(str).str[5:7]
#create a new column called 'Day' that is the day of the 'time' column
SSP126_2015_2039_tt['Day'] = SSP126_2015_2039_tt['time'].astype(str).str[8:10]
#create a new column called 'TimeSlice' that is 'M' + Month + 'D' + Day
SSP126_2015_2039_tt['TimeSlice'] = 'M' + SSP126_2015_2039_tt['Month'] + 'D' + SSP126_2015_2039_tt['Day']
# add a new column called 'Attribute' that is entirely full of 'RNW'
SSP126_2015_2039_tt['Attribute'] = 'NCAP_AF'
# add a new column called 'Yr' that is the year of the 'time' column
SSP126_2015_2039_tt['Yr'] = SSP126_2015_2039_tt['time'].astype(str).str[:4]
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_2015_2039_tt['PSET_CI'] = 'ELCWNO'

SSP126_2015_2039_tt= SSP126_2015_2039_tt.groupby(['State/Province', 'time']).first().compute()
#pivot the table so that TEMELE_REGIONS_COPY are the columns, TimeSlice are the rows, and the values are the CP
SSP126_2015_2039_tt = SSP126_2015_2039_tt.pivot_table(index=['TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI'], columns='State/Province', values='CP', aggfunc='first')
#replace all NaN values with 0
SSP126_2015_2039_tt = SSP126_2015_2039_tt.fillna(0)
# only keep TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI', 'Virginia', 'Rhode Island'
#SSP126_2015_2039_tt = SSP126_2015_2039_tt[['Virginia', 'Rhode Island']]
SSP126_2015_2039_tt

State/Province                                           Alaska   Arizona  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO   0.379232  0.193936
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO   0.286584  0.389142
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO   0.331932  0.331932
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO   0.379232  0.398658
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO   0.000000  0.411983
...                                                         ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO   0.000000  0.000000
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO   0.193936  0.420338
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO   0.379232  0.000000
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO   0.000000  0.322916
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO   0.193936  0.000000

State/Province                                         Arkansas  California  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO   0.000000    0.199734
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO   0.379232    0.223063
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO   0.193936    0.264736
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO   0.331932    0.255091
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO   0.193936    0.209639
...                                                         ...         ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO   0.379232    0.304333
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO   0.000000    0.332965
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO   0.421845    0.000000
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO   0.193936    0.291274
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO   0.379232    0.436877

State/Province                                         Colorado    Hawaii  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO   0.325733  0.359957
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO   0.376202  0.329381
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO   0.437365  0.461517
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO   0.443056  0.364068
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO   0.426408  0.358275
...                                                         ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO   0.415033  0.430811
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO   0.441405  0.409198
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO   0.250005  0.382922
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO   0.425481  0.326631
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO   0.309169  0.402983

State/Province                                            Idaho  Illinois  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO   0.262934  0.399398
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO   0.367710  0.415149
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO   0.314841  0.263591
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO   0.373532  0.302607
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO   0.382678  0.435930
...                                                         ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO   0.254529  0.385682
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO   0.000000  0.361898
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO   0.262934  0.434535
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO   0.193936  0.338985
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO   0.193936  0.410738

State/Province                                          Indiana      Iowa  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO   0.438794  0.405664
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO   0.408428  0.441417
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO   0.234048  0.415224
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO   0.379232  0.345406
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO   0.441041  0.448374
...                                                         ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO   0.395153  0.450926
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO   0.331932  0.403991
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO   0.421213  0.453741
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO   0.396247  0.423186
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO   0.403818  0.441300

State/Province                                         ...  South Dakota  \
TimeSlice Yr   Month Day time       Attribute PSET_CI  ...
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO   ...      0.431329
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO   ...      0.415132
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO   ...      0.425819
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO   ...      0.417266
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO   ...      0.447640
...                                                    ...           ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO   ...      0.446687
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO   ...      0.439863
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO   ...      0.445577
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO   ...      0.445536
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO   ...      0.411655

State/Province                                         Tennessee     Texas  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO    0.193936  0.387223
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO    0.000000  0.446887
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO    0.193936  0.443214
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO    0.000000  0.445269
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO    0.000000  0.356870
...                                                          ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO    0.448366  0.417132
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO    0.000000  0.416381
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO    0.414574  0.397461
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO    0.000000  0.428387
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO    0.000000  0.447960

State/Province                                             Utah   Vermont  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO   0.193936  0.448366
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO   0.000000  0.309258
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO   0.255701  0.438555
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO   0.343757  0.343757
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO   0.193936  0.420027
...                                                         ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO   0.000000  0.343757
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO   0.193936  0.343757
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO   0.000000  0.000000
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO   0.399367  0.445913
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO   0.000000  0.456123

State/Province                                         Virginia  Washington  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO   0.436877    0.331932
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO   0.000000    0.431269
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO   0.193936    0.414574
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO   0.000000    0.421706
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO   0.414574    0.211185
...                                                         ...         ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO   0.436877    0.000000
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO   0.000000    0.364628
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO   0.414574    0.000000
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO   0.193936    0.281782
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO   0.331932    0.331932

State/Province                                         West Virginia  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO        0.446197
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO        0.193936
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO        0.406720
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO        0.193936
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO        0.440857
...                                                              ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO        0.433085
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO        0.327544
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO        0.275248
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO        0.355582
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO        0.427109

State/Province                                         Wisconsin   Wyoming
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO    0.398036  0.434480
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO    0.409456  0.409663
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO    0.393739  0.432415
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO    0.324006  0.432615
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO    0.443076  0.412427
...                                                          ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO    0.436723  0.431242
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO    0.384341  0.402752
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO    0.433244  0.383467
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO    0.406277  0.386580
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO    0.364418  0.379486

[9131 rows x 40 columns]

In [20]:
#export to csv
SSP126_2015_2039_tt.to_csv('SSP126_projectedstatus_usa_offshore_2015_2039_TIMES_state.csv')

# 2040-2064

In [21]:
#create a new column called 'Month' that is the month of the 'time' column
SSP126_2040_2064_tt['Month'] = SSP126_2040_2064_tt['time'].astype(str).str[5:7]
#create a new column called 'Day' that is the day of the 'time' column
SSP126_2040_2064_tt['Day'] = SSP126_2040_2064_tt['time'].astype(str).str[8:10]
#create a new column called 'TimeSlice' that is 'M' + Month + 'D' + Day
SSP126_2040_2064_tt['TimeSlice'] = 'M' + SSP126_2040_2064_tt['Month'] + 'D' + SSP126_2040_2064_tt['Day']
# add a new column called 'Attribute' that is entirely full of 'RNW'
SSP126_2040_2064_tt['Attribute'] = 'NCAP_AF'
# add a new column called 'Yr' that is the year of the 'time' column
SSP126_2040_2064_tt['Yr'] = SSP126_2040_2064_tt['time'].astype(str).str[:4]
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_2040_2064_tt['PSET_CI'] = 'ELCWNF'


SSP126_2040_2064_tt= SSP126_2040_2064_tt.groupby(['State/Province', 'time']).first().compute()
#pivot the table so that TEMELE_REGIONS_COPY are the columns, TimeSlice are the rows, and the values are the CP
SSP126_2040_2064_tt = SSP126_2040_2064_tt.pivot_table(index=['TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI'], columns='State/Province', values='CP', aggfunc='first')
#replace all NaN values with 0
SSP126_2040_2064_tt = SSP126_2040_2064_tt.fillna(0)
# only keep TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI', 'Virginia', 'Rhode Island'
#SSP126_2040_2064_tt = SSP126_2040_2064_tt[['Virginia', 'Rhode Island']]
SSP126_2040_2064_tt

State/Province                                         California    Hawaii  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNF     0.367155  0.455180
          2041 01    01  2041-01-01 NCAP_AF   ELCWNF     0.426189  0.000000
          2042 01    01  2042-01-01 NCAP_AF   ELCWNF     0.387539  0.438555
          2043 01    01  2043-01-01 NCAP_AF   ELCWNF     0.310003  0.000000
          2044 01    01  2044-01-01 NCAP_AF   ELCWNF     0.436086  0.000000
...                                                           ...       ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNF     0.215382  0.421845
          2061 12    31  2061-12-31 NCAP_AF   ELCWNF     0.325043  0.331932
          2062 12    31  2062-12-31 NCAP_AF   ELCWNF     0.335561  0.414574
          2063 12    31  2063-12-31 NCAP_AF   ELCWNF     0.090205  0.379232
          2064 12    31  2064-12-31 NCAP_AF   ELCWNF     0.382503  0.331932

State/Province                                            Maine  Maryland  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNF   0.316793  0.300303
          2041 01    01  2041-01-01 NCAP_AF   ELCWNF   0.438555  0.383537
          2042 01    01  2042-01-01 NCAP_AF   ELCWNF   0.421845  0.359610
          2043 01    01  2043-01-01 NCAP_AF   ELCWNF   0.421845  0.102967
          2044 01    01  2044-01-01 NCAP_AF   ELCWNF   0.438555  0.317739
...                                                         ...       ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNF   0.436877  0.240432
          2061 12    31  2061-12-31 NCAP_AF   ELCWNF   0.414574  0.468629
          2062 12    31  2062-12-31 NCAP_AF   ELCWNF   0.421845  0.474780
          2063 12    31  2063-12-31 NCAP_AF   ELCWNF   0.193936  0.473251
          2064 12    31  2064-12-31 NCAP_AF   ELCWNF   0.456123  0.210864

State/Province                                         Massachusetts  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNF        0.084402
          2041 01    01  2041-01-01 NCAP_AF   ELCWNF        0.164101
          2042 01    01  2042-01-01 NCAP_AF   ELCWNF        0.247398
          2043 01    01  2043-01-01 NCAP_AF   ELCWNF        0.151734
          2044 01    01  2044-01-01 NCAP_AF   ELCWNF        0.156119
...                                                              ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNF        0.381980
          2061 12    31  2061-12-31 NCAP_AF   ELCWNF        0.368792
          2062 12    31  2062-12-31 NCAP_AF   ELCWNF        0.382924
          2063 12    31  2063-12-31 NCAP_AF   ELCWNF        0.437061
          2064 12    31  2064-12-31 NCAP_AF   ELCWNF        0.128578

State/Province                                         New Jersey  New York  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNF     0.362436  0.148022
          2041 01    01  2041-01-01 NCAP_AF   ELCWNF     0.394127  0.271946
          2042 01    01  2042-01-01 NCAP_AF   ELCWNF     0.384922  0.261727
          2043 01    01  2043-01-01 NCAP_AF   ELCWNF     0.334546  0.172095
          2044 01    01  2044-01-01 NCAP_AF   ELCWNF     0.380391  0.203461
...                                                           ...       ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNF     0.411478  0.430849
          2061 12    31  2061-12-31 NCAP_AF   ELCWNF     0.378529  0.439361
          2062 12    31  2062-12-31 NCAP_AF   ELCWNF     0.418446  0.356763
          2063 12    31  2063-12-31 NCAP_AF   ELCWNF     0.376721  0.447501
          2064 12    31  2064-12-31 NCAP_AF   ELCWNF     0.349006  0.169277

State/Province                                         North Carolina  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNF         0.340718
          2041 01    01  2041-01-01 NCAP_AF   ELCWNF         0.398819
          2042 01    01  2042-01-01 NCAP_AF   ELCWNF         0.424764
          2043 01    01  2043-01-01 NCAP_AF   ELCWNF         0.300287
          2044 01    01  2044-01-01 NCAP_AF   ELCWNF         0.417285
...                                                               ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNF         0.247461
          2061 12    31  2061-12-31 NCAP_AF   ELCWNF         0.390509
          2062 12    31  2062-12-31 NCAP_AF   ELCWNF         0.404541
          2063 12    31  2063-12-31 NCAP_AF   ELCWNF         0.474969
          2064 12    31  2064-12-31 NCAP_AF   ELCWNF         0.337579

State/Province                                             Ohio  Rhode Island  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNF   0.414574      0.452113
          2041 01    01  2041-01-01 NCAP_AF   ELCWNF   0.449057      0.448366
          2042 01    01  2042-01-01 NCAP_AF   ELCWNF   0.350062      0.438555
          2043 01    01  2043-01-01 NCAP_AF   ELCWNF   0.455180      0.455714
          2044 01    01  2044-01-01 NCAP_AF   ELCWNF   0.411422      0.449057
...                                                         ...           ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNF   0.444439      0.414574
          2061 12    31  2061-12-31 NCAP_AF   ELCWNF   0.436877      0.379232
          2062 12    31  2062-12-31 NCAP_AF   ELCWNF   0.225199      0.414574
          2063 12    31  2063-12-31 NCAP_AF   ELCWNF   0.455714      0.379232
          2064 12    31  2064-12-31 NCAP_AF   ELCWNF   0.456123      0.449057

State/Province                                         Virginia
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNF   0.450326
          2041 01    01  2041-01-01 NCAP_AF   ELCWNF   0.314227
          2042 01    01  2042-01-01 NCAP_AF   ELCWNF   0.390744
          2043 01    01  2043-01-01 NCAP_AF   ELCWNF   0.109932
          2044 01    01  2044-01-01 NCAP_AF   ELCWNF   0.277656
...                                                         ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNF   0.121904
          2061 12    31  2061-12-31 NCAP_AF   ELCWNF   0.312563
          2062 12    31  2062-12-31 NCAP_AF   ELCWNF   0.468683
          2063 12    31  2063-12-31 NCAP_AF   ELCWNF   0.459747
          2064 12    31  2064-12-31 NCAP_AF   ELCWNF   0.190575

[9132 rows x 11 columns]

In [22]:
#export to csv
SSP126_2040_2064_tt.to_csv('SSP126_projectedstatus_usa_offshore_2040_2064_TIMES_state.csv')

# 2065-2089

In [23]:
#   SSP 126 2065-2089
#create a new column called 'Month' that is the month of the 'time' column
SSP126_2065_2089_tt['Month'] = SSP126_2065_2089_tt['time'].astype(str).str[5:7]
#create a new column called 'Day' that is the day of the 'time' column
SSP126_2065_2089_tt['Day'] = SSP126_2065_2089_tt['time'].astype(str).str[8:10]
#create a new column called 'TimeSlice' that is 'M' + Month + 'D' + Day
SSP126_2065_2089_tt['TimeSlice'] = 'M' + SSP126_2065_2089_tt['Month'] + 'D' + SSP126_2065_2089_tt['Day']
# add a new column called 'Attribute' that is entirely full of 'RNW'
SSP126_2065_2089_tt['Attribute'] = 'NCAP_AF'
# add a new column called 'Yr' that is the year of the 'time' column
SSP126_2065_2089_tt['Yr'] = SSP126_2065_2089_tt['time'].astype(str).str[:4]
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_2065_2089_tt['PSET_CI'] = 'ELCWNF'

SSP126_2065_2089_tt= SSP126_2065_2089_tt.groupby(['State/Province', 'time']).first().compute()
#pivot the table so that TEMELE_REGIONS_COPY are the columns, TimeSlice are the rows, and the values are the CP
SSP126_2065_2089_tt = SSP126_2065_2089_tt.pivot_table(index=['TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI'], columns='State/Province', values='CP', aggfunc='first')
#replace all NaN values with 0
SSP126_2065_2089_tt = SSP126_2065_2089_tt.fillna(0)
# only keep TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI', 'Virginia', 'Rhode Island'
#SSP126_2065_2089_tt = SSP126_2065_2089_tt[['Virginia', 'Rhode Island']]
SSP126_2065_2089_tt

State/Province                                         California    Hawaii  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNF     0.443601  0.448366
          2066 01    01  2066-01-01 NCAP_AF   ELCWNF     0.426189  0.331932
          2067 01    01  2067-01-01 NCAP_AF   ELCWNF     0.307297  0.193936
          2068 01    01  2068-01-01 NCAP_AF   ELCWNF     0.426189  0.193936
          2069 01    01  2069-01-01 NCAP_AF   ELCWNF     0.332830  0.379232
...                                                           ...       ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNF     0.265262  0.448366
          2086 12    31  2086-12-31 NCAP_AF   ELCWNF     0.444617  0.444439
          2087 12    31  2087-12-31 NCAP_AF   ELCWNF     0.365147  0.000000
          2088 12    31  2088-12-31 NCAP_AF   ELCWNF     0.346693  0.000000
          2089 12    31  2089-12-31 NCAP_AF   ELCWNF     0.446248  0.438555

State/Province                                            Maine  Maryland  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNF   0.379232  0.174969
          2066 01    01  2066-01-01 NCAP_AF   ELCWNF   0.000000  0.473918
          2067 01    01  2067-01-01 NCAP_AF   ELCWNF   0.421845  0.426296
          2068 01    01  2068-01-01 NCAP_AF   ELCWNF   0.436877  0.423029
          2069 01    01  2069-01-01 NCAP_AF   ELCWNF   0.436877  0.401927
...                                                         ...       ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNF   0.438555  0.047574
          2086 12    31  2086-12-31 NCAP_AF   ELCWNF   0.436877  0.093484
          2087 12    31  2087-12-31 NCAP_AF   ELCWNF   0.331932  0.474780
          2088 12    31  2088-12-31 NCAP_AF   ELCWNF   0.421845  0.300303
          2089 12    31  2089-12-31 NCAP_AF   ELCWNF   0.414574  0.162758

State/Province                                         Massachusetts  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNF        0.440932
          2066 01    01  2066-01-01 NCAP_AF   ELCWNF        0.464167
          2067 01    01  2067-01-01 NCAP_AF   ELCWNF        0.349746
          2068 01    01  2068-01-01 NCAP_AF   ELCWNF        0.242437
          2069 01    01  2069-01-01 NCAP_AF   ELCWNF        0.200817
...                                                              ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNF        0.103113
          2086 12    31  2086-12-31 NCAP_AF   ELCWNF        0.102705
          2087 12    31  2087-12-31 NCAP_AF   ELCWNF        0.452270
          2088 12    31  2088-12-31 NCAP_AF   ELCWNF        0.194732
          2089 12    31  2089-12-31 NCAP_AF   ELCWNF        0.455402

State/Province                                         New Jersey  New York  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNF     0.355848  0.273217
          2066 01    01  2066-01-01 NCAP_AF   ELCWNF     0.408255  0.459532
          2067 01    01  2067-01-01 NCAP_AF   ELCWNF     0.406631  0.381258
          2068 01    01  2068-01-01 NCAP_AF   ELCWNF     0.397112  0.278319
          2069 01    01  2069-01-01 NCAP_AF   ELCWNF     0.371397  0.398325
...                                                           ...       ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNF     0.201124  0.108985
          2086 12    31  2086-12-31 NCAP_AF   ELCWNF     0.319213  0.136563
          2087 12    31  2087-12-31 NCAP_AF   ELCWNF     0.426491  0.411044
          2088 12    31  2088-12-31 NCAP_AF   ELCWNF     0.372732  0.251110
          2089 12    31  2089-12-31 NCAP_AF   ELCWNF     0.434219  0.443473

State/Province                                         North Carolina  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNF         0.303708
          2066 01    01  2066-01-01 NCAP_AF   ELCWNF         0.471723
          2067 01    01  2067-01-01 NCAP_AF   ELCWNF         0.348278
          2068 01    01  2068-01-01 NCAP_AF   ELCWNF         0.454300
          2069 01    01  2069-01-01 NCAP_AF   ELCWNF         0.422962
...                                                               ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNF         0.273164
          2086 12    31  2086-12-31 NCAP_AF   ELCWNF         0.282823
          2087 12    31  2087-12-31 NCAP_AF   ELCWNF         0.400307
          2088 12    31  2088-12-31 NCAP_AF   ELCWNF         0.346404
          2089 12    31  2089-12-31 NCAP_AF   ELCWNF         0.291446

State/Province                                             Ohio  Rhode Island  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNF   0.411422      0.379232
          2066 01    01  2066-01-01 NCAP_AF   ELCWNF   0.225199      0.331932
          2067 01    01  2067-01-01 NCAP_AF   ELCWNF   0.456123      0.414574
          2068 01    01  2068-01-01 NCAP_AF   ELCWNF   0.456123      0.436877
          2069 01    01  2069-01-01 NCAP_AF   ELCWNF   0.455714      0.421845
...                                                         ...           ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNF   0.411422      0.456123
          2086 12    31  2086-12-31 NCAP_AF   ELCWNF   0.438555      0.455180
          2087 12    31  2087-12-31 NCAP_AF   ELCWNF   0.225199      0.379232
          2088 12    31  2088-12-31 NCAP_AF   ELCWNF   0.331932      0.436877
          2089 12    31  2089-12-31 NCAP_AF   ELCWNF   0.449057      0.193936

State/Province                                         Virginia
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNF   0.151292
          2066 01    01  2066-01-01 NCAP_AF   ELCWNF   0.450326
          2067 01    01  2067-01-01 NCAP_AF   ELCWNF   0.314227
          2068 01    01  2068-01-01 NCAP_AF   ELCWNF   0.450326
          2069 01    01  2069-01-01 NCAP_AF   ELCWNF   0.426189
...                                                         ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNF   0.068761
          2086 12    31  2086-12-31 NCAP_AF   ELCWNF   0.082129
          2087 12    31  2087-12-31 NCAP_AF   ELCWNF   0.468683
          2088 12    31  2088-12-31 NCAP_AF   ELCWNF   0.215382
          2089 12    31  2089-12-31 NCAP_AF   ELCWNF   0.312563

[9131 rows x 11 columns]

In [24]:
#export to csv
SSP126_2065_2089_tt.to_csv('SSP126_projectedstatus_usa_offshore_2065_2089_TIMES_state.csv')

# 2090-2100

In [5]:
#   SSP 126 2090-2100

#create a new column called 'Month' that is the month of the 'time' column
SSP126_2090_2100_tt['Month'] = SSP126_2090_2100_tt['time'].astype(str).str[5:7]
#create a new column called 'Day' that is the day of the 'time' column
SSP126_2090_2100_tt['Day'] = SSP126_2090_2100_tt['time'].astype(str).str[8:10]
#create a new column called 'TimeSlice' that is 'M' + Month + 'D' + Day
SSP126_2090_2100_tt['TimeSlice'] = 'M' + SSP126_2090_2100_tt['Month'] + 'D' + SSP126_2090_2100_tt['Day']
# add a new column called 'Attribute' that is entirely full of 'RNW'
SSP126_2090_2100_tt['Attribute'] = 'NCAP_AF'
# add a new column called 'Yr' that is the year of the 'time' column
SSP126_2090_2100_tt['Yr'] = SSP126_2090_2100_tt['time'].astype(str).str[:4]
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_2090_2100_tt['PSET_CI'] = 'ELCWNO'


SSP126_2090_2100_tt= SSP126_2090_2100_tt.groupby(['State/Province', 'time']).first().compute()
#pivot the table so that TEMELE_REGIONS_COPY are the columns, TimeSlice are the rows, and the values are the CP
SSP126_2090_2100_tt = SSP126_2090_2100_tt.pivot_table(index=['TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI'], columns='State/Province', values='CP', aggfunc='first')
#replace all NaN values with 0
SSP126_2090_2100_tt = SSP126_2090_2100_tt.fillna(0)

# only keep TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI', 'Virginia', 'Rhode Island'
#SSP126_2090_2100_tt = SSP126_2090_2100_tt[['Virginia', 'Rhode Island']]

In [6]:
SSP126_2090_2100_tt

State/Province                                           Alaska   Arizona  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO   0.373253  0.255701
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO   0.286584  0.000000
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO   0.000000  0.000000
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO   0.000000  0.418649
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO   0.286584  0.421559
...                                                         ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO   0.436877  0.000000
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO   0.436877  0.000000
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO   0.262934  0.000000
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO   0.286584  0.422762
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO   0.436877  0.000000

State/Province                                         Arkansas  California  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO   0.000000    0.249095
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO   0.000000    0.412846
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO   0.379232    0.207730
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO   0.379232    0.337369
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO   0.193936    0.362531
...                                                         ...         ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO   0.449057    0.254671
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO   0.000000    0.307891
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO   0.000000    0.193936
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO   0.000000    0.342831
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO   0.438555    0.209225

State/Province                                         Colorado    Hawaii  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO   0.426836  0.396968
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO   0.430672  0.401119
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO   0.441575  0.437074
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO   0.279215  0.394550
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO   0.424714  0.389557
...                                                         ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO   0.359228  0.255407
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO   0.258334  0.399850
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO   0.364851  0.370343
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO   0.414109  0.413635
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO   0.424293  0.363670

State/Province                                            Idaho  Illinois  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO   0.354702  0.308522
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO   0.331932  0.306480
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO   0.390566  0.412507
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO   0.193936  0.193936
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO   0.000000  0.431833
...                                                         ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO   0.326833  0.452446
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO   0.193936  0.382263
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO   0.262934  0.337180
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO   0.000000  0.443928
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO   0.397244  0.452341

State/Province                                          Indiana      Iowa  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO   0.384859  0.433795
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO   0.416241  0.000000
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO   0.429688  0.438873
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO   0.193936  0.193936
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO   0.443601  0.444740
...                                                         ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO   0.447878  0.443462
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO   0.419676  0.417177
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO   0.423260  0.312014
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO   0.451930  0.391421
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO   0.446441  0.444224

State/Province                                         ...  South Dakota  \
TimeSlice Yr   Month Day time       Attribute PSET_CI  ...
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO   ...      0.440650
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO   ...      0.193936
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO   ...      0.454215
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO   ...      0.262934
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO   ...      0.443203
...                                                    ...           ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO   ...      0.428847
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO   ...      0.375005
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO   ...      0.413155
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO   ...      0.429857
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO   ...      0.367953

State/Province                                         Tennessee     Texas  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO    0.193936  0.405666
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO    0.193936  0.393509
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO    0.379232  0.439825
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO    0.000000  0.435185
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO    0.000000  0.381591
...                                                          ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO    0.193936  0.438186
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO    0.193936  0.374006
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO    0.000000  0.347000
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO    0.421845  0.377580
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO    0.436877  0.422849

State/Province                                             Utah   Vermont  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO   0.193936  0.343757
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO   0.000000  0.250913
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO   0.239935  0.193936
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO   0.379232  0.321083
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO   0.193936  0.398721
...                                                         ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO   0.286584  0.297433
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO   0.000000  0.274759
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO   0.331932  0.432233
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO   0.414574  0.449178
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO   0.402793  0.193936

State/Province                                         Virginia  Washington  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO   0.379232    0.193936
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO   0.438555    0.379229
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO   0.000000    0.426473
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO   0.000000    0.395707
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO   0.000000    0.304255
...                                                         ...         ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO   0.000000    0.323451
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO   0.421845    0.261592
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO   0.421845    0.411112
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO   0.452113    0.193936
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO   0.421845    0.379497

State/Province                                         West Virginia  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO        0.428580
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO        0.452602
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO        0.284144
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO        0.000000
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO        0.378190
...                                                              ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO        0.193936
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO        0.433226
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO        0.446350
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO        0.405605
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO        0.433632

State/Province                                         Wisconsin   Wyoming
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO    0.412159  0.426332
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO    0.413579  0.399014
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO    0.392180  0.428725
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO    0.274759  0.408333
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO    0.422553  0.390024
...                                                          ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO    0.440588  0.369103
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO    0.438316  0.193936
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO    0.407117  0.440048
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO    0.444656  0.393898
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO    0.451161  0.417487

[4017 rows x 40 columns]

In [7]:
#export to csv
SSP126_2090_2100_tt.to_csv('SSP126_projectedstatus_usa_onshore_2090_2100_TIMES_state.csv')

# Organize into TIMES Time Slices

In [8]:
import polars as pl

# Read all the *TIMES.csv files in Polars and concatenate them
SSP126_TIMES = pl.read_csv('SSP126_projectedstatus_usa_onshore_2015_2039_TIMES_state.csv')
SSP126_TIMES = SSP126_TIMES.extend(pl.read_csv('SSP126_projectedstatus_usa_onshore_2040_2064_TIMES_state.csv'))
SSP126_TIMES = SSP126_TIMES.extend(pl.read_csv('SSP126_projectedstatus_usa_onshore_2065_2089_TIMES_state.csv'))
SSP126_TIMES = SSP126_TIMES.extend(pl.read_csv('SSP126_projectedstatus_usa_onshore_2090_2100_TIMES_state.csv'))

# Filter the DataFrame to keep only rows with 'Yr' greater than or equal to 2020
SSP126_TIMES = SSP126_TIMES.filter(pl.col('Yr') >= 2020)

In [9]:
SSP126_TIMES.head()

shape: (5, 47)
┌───────────┬──────┬───────┬─────┬───┬────────────┬───────────────┬───────────┬──────────┐
│ TimeSlice ┆ Yr   ┆ Month ┆ Day ┆ … ┆ Washington ┆ West Virginia ┆ Wisconsin ┆ Wyoming  │
│ ---       ┆ ---  ┆ ---   ┆ --- ┆   ┆ ---        ┆ ---           ┆ ---       ┆ ---      │
│ str       ┆ i64  ┆ i64   ┆ i64 ┆   ┆ f64        ┆ f64           ┆ f64       ┆ f64      │
╞═══════════╪══════╪═══════╪═════╪═══╪════════════╪═══════════════╪═══════════╪══════════╡
│ M01D01    ┆ 2020 ┆ 1     ┆ 1   ┆ … ┆ 0.414521   ┆ 0.331932      ┆ 0.425964  ┆ 0.369438 │
│ M01D01    ┆ 2021 ┆ 1     ┆ 1   ┆ … ┆ 0.193936   ┆ 0.193936      ┆ 0.429076  ┆ 0.429615 │
│ M01D01    ┆ 2022 ┆ 1     ┆ 1   ┆ … ┆ 0.366954   ┆ 0.398171      ┆ 0.0       ┆ 0.43621  │
│ M01D01    ┆ 2023 ┆ 1     ┆ 1   ┆ … ┆ 0.41264    ┆ 0.224602      ┆ 0.379403  ┆ 0.376156 │
│ M01D01    ┆ 2024 ┆ 1     ┆ 1   ┆ … ┆ 0.398463   ┆ 0.265779      ┆ 0.4335385 ┆ 0.262668 │
└───────────┴──────┴───────┴─────┴───┴────────────┴───────────────┴───────────┴──────────┘

In [10]:
import polars as pl

# Add 'Season' column based on the 'Month' column
SSP126_TIMES = SSP126_TIMES.with_columns(
    Season=
    SSP126_TIMES["Month"].apply(
        lambda month: "S01" if month in [1, 2, 12] else "S02" if month in [3, 4, 5] else "S03" if month in [6, 7, 8] else "S04"
    ),
)

#read 'time' column as datetime 

SSP126_TIMES = SSP126_TIMES.with_columns(pl.col('time').str.strptime(pl.Datetime).alias('time'))

# find the weekday number of the 'time' column 
SSP126_TIMES = SSP126_TIMES.with_columns(
    Weekday=
    SSP126_TIMES["time"].apply(
        lambda time: time.isoweekday()
    ),
)

# if the 'Weekday' is equal to 6, 2, 3, 4, or 5, then the 'Type' is 'WD2', otherwise it is 'WD1'
SSP126_TIMES = SSP126_TIMES.with_columns(
    Type=
    SSP126_TIMES["Weekday"].apply(
        lambda Weekday: "WD2" if Weekday in [6, 2, 3, 4, 5] else "WD1"
    ),
)

SSP126_TIMES = SSP126_TIMES.with_columns(pl.lit('NCAP_AF').alias('Attribute'))

In [11]:
SSP126_TIMES

shape: (29_585, 50)
┌───────────┬──────┬───────┬─────┬───┬──────────┬────────┬─────────┬──────┐
│ TimeSlice ┆ Yr   ┆ Month ┆ Day ┆ … ┆ Wyoming  ┆ Season ┆ Weekday ┆ Type │
│ ---       ┆ ---  ┆ ---   ┆ --- ┆   ┆ ---      ┆ ---    ┆ ---     ┆ ---  │
│ str       ┆ i64  ┆ i64   ┆ i64 ┆   ┆ f64      ┆ str    ┆ i64     ┆ str  │
╞═══════════╪══════╪═══════╪═════╪═══╪══════════╪════════╪═════════╪══════╡
│ M01D01    ┆ 2020 ┆ 1     ┆ 1   ┆ … ┆ 0.369438 ┆ S01    ┆ 3       ┆ WD2  │
│ M01D01    ┆ 2021 ┆ 1     ┆ 1   ┆ … ┆ 0.429615 ┆ S01    ┆ 5       ┆ WD2  │
│ M01D01    ┆ 2022 ┆ 1     ┆ 1   ┆ … ┆ 0.43621  ┆ S01    ┆ 6       ┆ WD2  │
│ M01D01    ┆ 2023 ┆ 1     ┆ 1   ┆ … ┆ 0.376156 ┆ S01    ┆ 7       ┆ WD1  │
│ …         ┆ …    ┆ …     ┆ …   ┆ … ┆ …        ┆ …      ┆ …       ┆ …    │
│ M12D31    ┆ 2097 ┆ 12    ┆ 31  ┆ … ┆ 0.193936 ┆ S01    ┆ 2       ┆ WD2  │
│ M12D31    ┆ 2098 ┆ 12    ┆ 31  ┆ … ┆ 0.440048 ┆ S01    ┆ 3       ┆ WD2  │
│ M12D31    ┆ 2099 ┆ 12    ┆ 31  ┆ … ┆ 0.393898 ┆ S01    ┆ 4       ┆ WD2  │
│ M12D31    ┆ 2100 ┆ 12    ┆ 31  ┆ … ┆ 0.417487 ┆ S01    ┆ 5       ┆ WD2  │
└───────────┴──────┴───────┴─────┴───┴──────────┴────────┴─────────┴──────┘

# TS - 8760
Daily/hourly values. Ex: January 1, 2020 in USA

In [12]:

SSP126_TIMES.head()

shape: (5, 50)
┌───────────┬──────┬───────┬─────┬───┬──────────┬────────┬─────────┬──────┐
│ TimeSlice ┆ Yr   ┆ Month ┆ Day ┆ … ┆ Wyoming  ┆ Season ┆ Weekday ┆ Type │
│ ---       ┆ ---  ┆ ---   ┆ --- ┆   ┆ ---      ┆ ---    ┆ ---     ┆ ---  │
│ str       ┆ i64  ┆ i64   ┆ i64 ┆   ┆ f64      ┆ str    ┆ i64     ┆ str  │
╞═══════════╪══════╪═══════╪═════╪═══╪══════════╪════════╪═════════╪══════╡
│ M01D01    ┆ 2020 ┆ 1     ┆ 1   ┆ … ┆ 0.369438 ┆ S01    ┆ 3       ┆ WD2  │
│ M01D01    ┆ 2021 ┆ 1     ┆ 1   ┆ … ┆ 0.429615 ┆ S01    ┆ 5       ┆ WD2  │
│ M01D01    ┆ 2022 ┆ 1     ┆ 1   ┆ … ┆ 0.43621  ┆ S01    ┆ 6       ┆ WD2  │
│ M01D01    ┆ 2023 ┆ 1     ┆ 1   ┆ … ┆ 0.376156 ┆ S01    ┆ 7       ┆ WD1  │
│ M01D01    ┆ 2024 ┆ 1     ┆ 1   ┆ … ┆ 0.262668 ┆ S01    ┆ 1       ┆ WD1  │
└───────────┴──────┴───────┴─────┴───┴──────────┴────────┴─────────┴──────┘

In [13]:
# save to csv 
SSP126_TIMES.write_csv('SSP126_projectedstatus_usa_onshore_TS8760_TUSM.csv') # Onshore
#SSP126_TIMES.write_csv('SSP585_Offshore_TS8760_TUSM.csv') # Offshore

# TS - 120
Averaged by month and weekday type by country. ex: Weekdays in January in 2020 in USA, Weekends in January in 2020 in USA

In [36]:
# Group by year, month, type, then calculate the average for each groupby 
#groupby the Yr and Season and find mean 
SSP126_TIMES_120 = SSP126_TIMES.groupby(['Yr', 'Month', 'Type']).mean()
# sort by year and season
SSP126_TIMES_120 = SSP126_TIMES_120.sort(['Yr', 'Month'])
# make all rows in the 'PSET_CI' column 'ELCWNF' in polars
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_TIMES_120 = SSP126_TIMES_120.with_columns(pl.col('PSET_CI').fill_null('ELCWNF'))
# do the same but RNW for Attribute
SSP126_TIMES_120 = SSP126_TIMES_120.with_columns(pl.col('Attribute').fill_null('NCAP_AF'))
# make a column called 'M' that is just 'M' + Month
SSP126_TIMES_120 = SSP126_TIMES_120.with_columns(pl.lit('M').alias('M'))
#create a new column called 'TimeSlice' that is 'M' + Month + Type
SSP126_TIMES_120 = SSP126_TIMES_120.with_columns(pl.concat_str([pl.col('M'), pl.col('Month').cast(pl.Utf8).str.zfill(2), pl.col('Type')], separator='').alias('TimeSlice'))
# drop TimeSlice, time, Attribute, and PSET_CI columns
SSP126_TIMES_120 = SSP126_TIMES_120.drop(['Day', 'time', 'Type', 'M', 'Season', 'Weekday', 'Month'])

SSP126_TIMES_120

shape: (1_944, 15)
┌──────┬───────────┬───────────┬─────────┬───┬──────────┬──────────┬──────────────┬───────────┐
│ Yr   ┆ TimeSlice ┆ Attribute ┆ PSET_CI ┆ … ┆ North    ┆ Ohio     ┆ Rhode Island ┆ Virginia  │
│ ---  ┆ ---       ┆ ---       ┆ ---     ┆   ┆ Carolina ┆ ---      ┆ ---          ┆ ---       │
│ i64  ┆ str       ┆ str       ┆ str     ┆   ┆ ---      ┆ f64      ┆ f64          ┆ f64       │
│      ┆           ┆           ┆         ┆   ┆ f64      ┆          ┆              ┆           │
╞══════╪═══════════╪═══════════╪═════════╪═══╪══════════╪══════════╪══════════════╪═══════════╡
│ 2020 ┆ M01WD1    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.312962 ┆ 0.316171 ┆ 0.38562      ┆ 0.1495365 │
│ 2020 ┆ M01WD2    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.384863 ┆ 0.337249 ┆ 0.372023     ┆ 0.334215  │
│ 2020 ┆ M02WD1    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.360722 ┆ 0.379495 ┆ 0.420599     ┆ 0.289213  │
│ 2020 ┆ M02WD2    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.384851 ┆ 0.439158 ┆ 0.40201      ┆ 0.332699  │
│ …    ┆ …         ┆ …         ┆ …       ┆ … ┆ …        ┆ …        ┆ …            ┆ …         │
│ 2100 ┆ M11WD1    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.399095 ┆ 0.420338 ┆ 0.407084     ┆ 0.362312  │
│ 2100 ┆ M11WD2    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.354037 ┆ 0.421283 ┆ 0.380129     ┆ 0.304084  │
│ 2100 ┆ M12WD1    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.339107 ┆ 0.41222  ┆ 0.37129      ┆ 0.310154  │
│ 2100 ┆ M12WD2    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.378912 ┆ 0.378781 ┆ 0.361588     ┆ 0.348118  │
└──────┴───────────┴───────────┴─────────┴───┴──────────┴──────────┴──────────────┴───────────┘

In [37]:
# save to csv 
SSP126_TIMES_120.write_csv('SSP126_projectedstatus_usa_offshore_TS120_TUSM.csv') # Onshore
#SSP126_TIMES_120.write_csv('SSP585_Offshore_TS120_TUSM.csv') # Offshore

# TS - 40
Averaged by season and weekday type by country. ex: Weekdays in Fall in 2020 in USA, Weekends in Fall in 2020 in USA

In [38]:
#groupby the Yr and Season and find mean 
SSP126_TIMES_40 = SSP126_TIMES.groupby(['Yr', 'Season', 'Type']).mean()
# sort by year and season
SSP126_TIMES_40 = SSP126_TIMES_40.sort(['Yr', 'Season'])
# drop TimeSlice, time, Attribute, and PSET_CI columns
SSP126_TIMES_40 = SSP126_TIMES_40.drop(['TimeSlice', 'time', 'Weekday', 'Month', 'Day'])
# make all rows in the 'PSET_CI' column 'ELCWNF' in polars
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_TIMES_40 = SSP126_TIMES_40.with_columns(pl.col('PSET_CI').fill_null('ELCWNF'))
# do the same but RNW for Attribute
SSP126_TIMES_40 = SSP126_TIMES_40.with_columns(pl.col('Attribute').fill_null('NCAP_AF'))
#Create a column called 'TimeSlice' that is the Season + Type
SSP126_TIMES_40 = SSP126_TIMES_40.with_columns(pl.concat_str([pl.col('Season'), pl.col('Type')], separator='').alias('TimeSlice'))
# drop the Season and Type columns
SSP126_TIMES_40 = SSP126_TIMES_40.drop(['Season', 'Type'])

SSP126_TIMES_40

shape: (648, 15)
┌──────┬───────────┬─────────┬────────────┬───┬──────────┬──────────────┬──────────┬───────────┐
│ Yr   ┆ Attribute ┆ PSET_CI ┆ California ┆ … ┆ Ohio     ┆ Rhode Island ┆ Virginia ┆ TimeSlice │
│ ---  ┆ ---       ┆ ---     ┆ ---        ┆   ┆ ---      ┆ ---          ┆ ---      ┆ ---       │
│ i64  ┆ str       ┆ str     ┆ f64        ┆   ┆ f64      ┆ f64          ┆ f64      ┆ str       │
╞══════╪═══════════╪═════════╪════════════╪═══╪══════════╪══════════════╪══════════╪═══════════╡
│ 2020 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.341716   ┆ … ┆ 0.372182 ┆ 0.399591     ┆ 0.320933 ┆ S01WD2    │
│ 2020 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.329089   ┆ … ┆ 0.346224 ┆ 0.372148     ┆ 0.253699 ┆ S01WD1    │
│ 2020 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.373289   ┆ … ┆ 0.399077 ┆ 0.362964     ┆ 0.405686 ┆ S02WD1    │
│ 2020 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.338082   ┆ … ┆ 0.432302 ┆ 0.353424     ┆ 0.373274 ┆ S02WD2    │
│ …    ┆ …         ┆ …       ┆ …          ┆ … ┆ …        ┆ …            ┆ …        ┆ …         │
│ 2100 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.340692   ┆ … ┆ 0.400478 ┆ 0.322506     ┆ 0.366568 ┆ S03WD2    │
│ 2100 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.36608    ┆ … ┆ 0.420115 ┆ 0.30016      ┆ 0.400157 ┆ S03WD1    │
│ 2100 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.366873   ┆ … ┆ 0.43147  ┆ 0.35994      ┆ 0.327081 ┆ S04WD1    │
│ 2100 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.349322   ┆ … ┆ 0.388738 ┆ 0.386443     ┆ 0.354975 ┆ S04WD2    │
└──────┴───────────┴─────────┴────────────┴───┴──────────┴──────────────┴──────────┴───────────┘

In [39]:
# save to csv 
SSP126_TIMES_40.write_csv('SSP126_projectedstatus_usa_offshore_TS40_TUSM.csv') # Onshore
#SSP126_TIMES_40.write_csv('SSP585_Offshore_TS40_TUSM.csv') # Offshore

# TS - 1
Averaged annually by country. ex: 2020 in USA

In [40]:

#groupby the Yr and find mean 
SSP126_TIMES_1 = SSP126_TIMES.groupby(['Yr']).mean()
# sort by year and season
SSP126_TIMES_1 = SSP126_TIMES_1.sort(['Yr'])
# drop TimeSlice, time, Attribute, and PSET_CI columns
SSP126_TIMES_1 = SSP126_TIMES_1.drop(['TimeSlice', 'time', 'Weekday', 'Month', 'Day', 'Season', 'Type'])
# make all rows in the 'PSET_CI' column 'ELCWNF' in polars
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_TIMES_1 = SSP126_TIMES_1.with_columns(pl.col('PSET_CI').fill_null('ELCWNF'))
# do the same but RNW for Attribute
SSP126_TIMES_1 = SSP126_TIMES_1.with_columns(pl.col('Attribute').fill_null('NCAP_AF'))
SSP126_TIMES_1.head()

shape: (5, 14)
┌──────┬───────────┬─────────┬────────────┬───┬──────────┬──────────┬──────────────┬──────────┐
│ Yr   ┆ Attribute ┆ PSET_CI ┆ California ┆ … ┆ North    ┆ Ohio     ┆ Rhode Island ┆ Virginia │
│ ---  ┆ ---       ┆ ---     ┆ ---        ┆   ┆ Carolina ┆ ---      ┆ ---          ┆ ---      │
│ i64  ┆ str       ┆ str     ┆ f64        ┆   ┆ ---      ┆ f64      ┆ f64          ┆ f64      │
│      ┆           ┆         ┆            ┆   ┆ f64      ┆          ┆              ┆          │
╞══════╪═══════════╪═════════╪════════════╪═══╪══════════╪══════════╪══════════════╪══════════╡
│ 2020 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.34297    ┆ … ┆ 0.380842 ┆ 0.405722 ┆ 0.369974     ┆ 0.344496 │
│ 2021 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.338307   ┆ … ┆ 0.383525 ┆ 0.391292 ┆ 0.345772     ┆ 0.362282 │
│ 2022 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.339563   ┆ … ┆ 0.379112 ┆ 0.406055 ┆ 0.34491      ┆ 0.345138 │
│ 2023 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.339638   ┆ … ┆ 0.386703 ┆ 0.410141 ┆ 0.342815     ┆ 0.3617   │
│ 2024 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.335466   ┆ … ┆ 0.384058 ┆ 0.403839 ┆ 0.326717     ┆ 0.355293 │
└──────┴───────────┴─────────┴────────────┴───┴──────────┴──────────┴──────────────┴──────────┘

In [41]:
# save to csv 
SSP126_TIMES_1.write_csv('SSP126_projectedstatus_usa_offshore_TS1_TUSM.csv') # Onshore
#SSP126_TIMES_1.write_csv('SSP585_Offshore_TS1_TUSM.csv') # Offshore

For New Method

The following cells for work TS40 and TS120, for 8760, see furthur below.

In [42]:
import pandas as pd
test = pd.read_excel('SSP126_projectedstatus_usa_offshore_TS120_TUSM.xlsx')
test

,Yr,TimeSlice,Attribute,PSET_CI,US_CA,US_ME,US_MD,US_MA,US_NJ,US_NY,US_NC,US_OH,US_RI,US_VA
0,2020,M01WD1,NCAP_AF,ELCWNF,0.286698,0.376471,0.190097,0.203570,0.354587,0.205239,0.312962,0.316171,0.385620,0.149536
1,2020,M01WD2,NCAP_AF,ELCWNF,0.355211,0.366695,0.329901,0.277034,0.370826,0.289668,0.384863,0.337249,0.372023,0.334215
2,2020,M02WD1,NCAP_AF,ELCWNF,0.374478,0.369360,0.287097,0.286724,0.376764,0.286427,0.360722,0.379495,0.420599,0.289213
3,2020,M02WD2,NCAP_AF,ELCWNF,0.322084,0.396077,0.335768,0.305159,0.382643,0.323197,0.384851,0.439158,0.402010,0.332699
4,2020,M03WD1,NCAP_AF,ELCWNF,0.381255,0.395439,0.375770,0.332016,0.404860,0.347040,0.359625,0.351932,0.429631,0.393335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1939,2100,M10WD1,NCAP_AF,ELCWNF,0.405480,0.374525,0.396805,0.365903,0.400569,0.395979,0.386308,0.441814,0.415563,0.363538
1940,2100,M11WD1,NCAP_AF,ELCWNF,0.356262,0.416694,0.375151,0.293063,0.392486,0.306645,0.399095,0.420338,0.407084,0.362312
1941,2100,M11WD2,NCAP_AF,ELCWNF,0.365066,0.384257,0.339468,0.294606,0.365184,0.307808,0.354037,0.421283,0.380129,0.304084
1942,2100,M12WD1,NCAP_AF,ELCWNF,0.342766,0.341850,0.337978,0.324273,0.367376,0.334688,0.339107,0.412220,0.371290,0.310154
1943,2100,M12WD2,NCAP_AF,ELCWNF,0.361396,0.295797,0.355909,0.329377,0.381392,0.332247,0.378912,0.378781,0.361588,0.348118

In [43]:
# Here you add the 'AllRegions' column values together by TimeSlice. 

timeslice_120 = [
    ["M01WD1", 0.021857923],
    ["M01WD2", 0.06284153],
    ["M02WD1", 0.024590164],
    ["M02WD2", 0.054644809],
    ["M03WD1", 0.024590164],
    ["M03WD2", 0.06010929],
    ["M04WD1", 0.021857923],
    ["M04WD2", 0.06010929],
    ["M05WD1", 0.027322404],
    ["M05WD2", 0.057377049],
    ["M06WD1", 0.021857923],
    ["M06WD2", 0.06010929],
    ["M07WD1", 0.021857923],
    ["M07WD2", 0.06284153],
    ["M08WD1", 0.027322404],
    ["M08WD2", 0.057377049],
    ["M09WD1", 0.021857923],
    ["M09WD2", 0.06010929],
    ["M10WD1", 0.024590164],
    ["M10WD2", 0.06010929],
    ["M11WD1", 0.024590164],
    ["M11WD2", 0.057377049],
    ["M12WD1", 0.021857923],
    ["M12WD2", 0.06284153]
]

timeslice_ts40 = [
    ["S01WD1", 0.068306011],
    ["S01WD2", 0.180327869],
    ["S02WD1", 0.073770492],
    ["S02WD2", 0.177595628],
    ["S03WD1", 0.071038251],
    ["S03WD2", 0.180327869],
    ["S04WD1", 0.071038251],
    ["S04WD2", 0.177595628]
]

columns = ["TimeSlice", "Sum"]

timeslice = pd.DataFrame(timeslice_120, columns=columns)

timeslice

   TimeSlice       Sum
0     M01WD1  0.021858
1     M01WD2  0.062842
2     M02WD1  0.024590
3     M02WD2  0.054645
4     M03WD1  0.024590
5     M03WD2  0.060109
6     M04WD1  0.021858
7     M04WD2  0.060109
8     M05WD1  0.027322
9     M05WD2  0.057377
10    M06WD1  0.021858
11    M06WD2  0.060109
12    M07WD1  0.021858
13    M07WD2  0.062842
14    M08WD1  0.027322
15    M08WD2  0.057377
16    M09WD1  0.021858
17    M09WD2  0.060109
18    M10WD1  0.024590
19    M10WD2  0.060109
20    M11WD1  0.024590
21    M11WD2  0.057377
22    M12WD1  0.021858
23    M12WD2  0.062842

In [44]:
# merge the two on the 'TimeSlice' column
test = pd.merge(test, timeslice, on='TimeSlice', how='left')
test

,Yr,TimeSlice,Attribute,PSET_CI,US_CA,US_ME,US_MD,US_MA,US_NJ,US_NY,US_NC,US_OH,US_RI,US_VA,Sum
0,2020,M01WD1,NCAP_AF,ELCWNF,0.286698,0.376471,0.190097,0.203570,0.354587,0.205239,0.312962,0.316171,0.385620,0.149536,0.021858
1,2020,M01WD2,NCAP_AF,ELCWNF,0.355211,0.366695,0.329901,0.277034,0.370826,0.289668,0.384863,0.337249,0.372023,0.334215,0.062842
2,2020,M02WD1,NCAP_AF,ELCWNF,0.374478,0.369360,0.287097,0.286724,0.376764,0.286427,0.360722,0.379495,0.420599,0.289213,0.024590
3,2020,M02WD2,NCAP_AF,ELCWNF,0.322084,0.396077,0.335768,0.305159,0.382643,0.323197,0.384851,0.439158,0.402010,0.332699,0.054645
4,2020,M03WD1,NCAP_AF,ELCWNF,0.381255,0.395439,0.375770,0.332016,0.404860,0.347040,0.359625,0.351932,0.429631,0.393335,0.024590
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1939,2100,M10WD1,NCAP_AF,ELCWNF,0.405480,0.374525,0.396805,0.365903,0.400569,0.395979,0.386308,0.441814,0.415563,0.363538,0.024590
1940,2100,M11WD1,NCAP_AF,ELCWNF,0.356262,0.416694,0.375151,0.293063,0.392486,0.306645,0.399095,0.420338,0.407084,0.362312,0.024590
1941,2100,M11WD2,NCAP_AF,ELCWNF,0.365066,0.384257,0.339468,0.294606,0.365184,0.307808,0.354037,0.421283,0.380129,0.304084,0.057377
1942,2100,M12WD1,NCAP_AF,ELCWNF,0.342766,0.341850,0.337978,0.324273,0.367376,0.334688,0.339107,0.412220,0.371290,0.310154,0.021858
1943,2100,M12WD2,NCAP_AF,ELCWNF,0.361396,0.295797,0.355909,0.329377,0.381392,0.332247,0.378912,0.378781,0.361588,0.348118,0.062842

In [45]:
# List of US_* column names
us_columns = [col for col in test.columns if col.startswith('US_')]

# Loop through the US_* columns and create new columns
for col in us_columns:
    new_col_name = col + '_n'  # New column name
    test[new_col_name] = test['Sum'] * test[col]

In [46]:
test

,Yr,TimeSlice,Attribute,PSET_CI,US_CA,US_ME,US_MD,US_MA,US_NJ,US_NY,...,US_CA_n,US_ME_n,US_MD_n,US_MA_n,US_NJ_n,US_NY_n,US_NC_n,US_OH_n,US_RI_n,US_VA_n
0,2020,M01WD1,NCAP_AF,ELCWNF,0.286698,0.376471,0.190097,0.203570,0.354587,0.205239,...,0.006267,0.008229,0.004155,0.004450,0.007751,0.004486,0.006841,0.006911,0.008429,0.003269
1,2020,M01WD2,NCAP_AF,ELCWNF,0.355211,0.366695,0.329901,0.277034,0.370826,0.289668,...,0.022322,0.023044,0.020732,0.017409,0.023303,0.018203,0.024185,0.021193,0.023378,0.021003
2,2020,M02WD1,NCAP_AF,ELCWNF,0.374478,0.369360,0.287097,0.286724,0.376764,0.286427,...,0.009208,0.009083,0.007060,0.007051,0.009265,0.007043,0.008870,0.009332,0.010343,0.007112
3,2020,M02WD2,NCAP_AF,ELCWNF,0.322084,0.396077,0.335768,0.305159,0.382643,0.323197,...,0.017600,0.021644,0.018348,0.016675,0.020909,0.017661,0.021030,0.023998,0.021968,0.018180
4,2020,M03WD1,NCAP_AF,ELCWNF,0.381255,0.395439,0.375770,0.332016,0.404860,0.347040,...,0.009375,0.009724,0.009240,0.008164,0.009956,0.008534,0.008843,0.008654,0.010565,0.009672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1939,2100,M10WD1,NCAP_AF,ELCWNF,0.405480,0.374525,0.396805,0.365903,0.400569,0.395979,...,0.009971,0.009210,0.009758,0.008998,0.009850,0.009737,0.009499,0.010864,0.010219,0.008939
1940,2100,M11WD1,NCAP_AF,ELCWNF,0.356262,0.416694,0.375151,0.293063,0.392486,0.306645,...,0.008761,0.010247,0.009225,0.007206,0.009651,0.007540,0.009814,0.010336,0.010010,0.008909
1941,2100,M11WD2,NCAP_AF,ELCWNF,0.365066,0.384257,0.339468,0.294606,0.365184,0.307808,...,0.020946,0.022048,0.019478,0.016904,0.020953,0.017661,0.020314,0.024172,0.021811,0.017447
1942,2100,M12WD1,NCAP_AF,ELCWNF,0.342766,0.341850,0.337978,0.324273,0.367376,0.334688,...,0.007492,0.007472,0.007388,0.007088,0.008030,0.007316,0.007412,0.009010,0.008116,0.006779
1943,2100,M12WD2,NCAP_AF,ELCWNF,0.361396,0.295797,0.355909,0.329377,0.381392,0.332247,...,0.022711,0.018588,0.022366,0.020699,0.023967,0.020879,0.023811,0.023803,0.022723,0.021876

In [47]:
test['Sum']

0       0.021858
1       0.062842
2       0.024590
3       0.054645
4       0.024590
          ...
1939    0.024590
1940    0.024590
1941    0.057377
1942    0.021858
1943    0.062842
Name: Sum, Length: 1944, dtype: float64

In [48]:
# drop the us_columns in test 
test = test.drop(us_columns, axis=1)
test

,Yr,TimeSlice,Attribute,PSET_CI,Sum,US_CA_n,US_ME_n,US_MD_n,US_MA_n,US_NJ_n,US_NY_n,US_NC_n,US_OH_n,US_RI_n,US_VA_n
0,2020,M01WD1,NCAP_AF,ELCWNF,0.021858,0.006267,0.008229,0.004155,0.004450,0.007751,0.004486,0.006841,0.006911,0.008429,0.003269
1,2020,M01WD2,NCAP_AF,ELCWNF,0.062842,0.022322,0.023044,0.020732,0.017409,0.023303,0.018203,0.024185,0.021193,0.023378,0.021003
2,2020,M02WD1,NCAP_AF,ELCWNF,0.024590,0.009208,0.009083,0.007060,0.007051,0.009265,0.007043,0.008870,0.009332,0.010343,0.007112
3,2020,M02WD2,NCAP_AF,ELCWNF,0.054645,0.017600,0.021644,0.018348,0.016675,0.020909,0.017661,0.021030,0.023998,0.021968,0.018180
4,2020,M03WD1,NCAP_AF,ELCWNF,0.024590,0.009375,0.009724,0.009240,0.008164,0.009956,0.008534,0.008843,0.008654,0.010565,0.009672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1939,2100,M10WD1,NCAP_AF,ELCWNF,0.024590,0.009971,0.009210,0.009758,0.008998,0.009850,0.009737,0.009499,0.010864,0.010219,0.008939
1940,2100,M11WD1,NCAP_AF,ELCWNF,0.024590,0.008761,0.010247,0.009225,0.007206,0.009651,0.007540,0.009814,0.010336,0.010010,0.008909
1941,2100,M11WD2,NCAP_AF,ELCWNF,0.057377,0.020946,0.022048,0.019478,0.016904,0.020953,0.017661,0.020314,0.024172,0.021811,0.017447
1942,2100,M12WD1,NCAP_AF,ELCWNF,0.021858,0.007492,0.007472,0.007388,0.007088,0.008030,0.007316,0.007412,0.009010,0.008116,0.006779
1943,2100,M12WD2,NCAP_AF,ELCWNF,0.062842,0.022711,0.018588,0.022366,0.020699,0.023967,0.020879,0.023811,0.023803,0.022723,0.021876

In [49]:
# group by Year and find the sum of each column, rename each column with '_sum' at the end
test_sum = test.groupby('Yr').sum().add_suffix('_sum').reset_index()

In [50]:
test_sum

,Yr,TimeSlice_sum,Attribute_sum,PSET_CI_sum,Sum_sum,US_CA_n_sum,US_ME_n_sum,US_MD_n_sum,US_MA_n_sum,US_NJ_n_sum,US_NY_n_sum,US_NC_n_sum,US_OH_n_sum,US_RI_n_sum,US_VA_n_sum
0,2020,M01WD1M01WD2M02WD1M02WD2M03WD1M03WD2M04WD1M04W...,NCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP...,ELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCW...,1.0,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.406380,0.369749,0.344388
1,2021,M01WD2M01WD1M02WD1M02WD2M03WD2M03WD1M04WD2M04W...,NCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP...,ELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCW...,1.0,0.338565,0.316173,0.374735,0.349090,0.378902,0.360969,0.383587,0.391410,0.345681,0.362408
2,2022,M01WD2M01WD1M02WD2M02WD1M03WD1M03WD2M04WD1M04W...,NCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP...,ELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCW...,1.0,0.340072,0.335224,0.365355,0.343063,0.377283,0.358082,0.379014,0.406558,0.345071,0.345181
3,2023,M01WD1M01WD2M02WD2M02WD1M03WD1M03WD2M04WD1M04W...,NCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP...,ELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCW...,1.0,0.339760,0.312694,0.375291,0.353192,0.374916,0.366862,0.386154,0.410239,0.343986,0.360838
4,2024,M01WD2M01WD1M02WD2M02WD1M03WD1M03WD2M04WD1M04W...,NCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP...,ELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCW...,1.0,0.335654,0.300267,0.359110,0.350513,0.366921,0.357800,0.383888,0.403003,0.327977,0.354935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,2096,M01WD1M01WD2M02WD1M02WD2M03WD1M03WD2M04WD2M04W...,NCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP...,ELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCW...,1.0,0.345507,0.330593,0.354488,0.335432,0.368308,0.342753,0.381822,0.390716,0.375856,0.347887
77,2097,M01WD2M01WD1M02WD1M02WD2M03WD1M03WD2M04WD2M04W...,NCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP...,ELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCW...,1.0,0.345544,0.328079,0.361596,0.333087,0.374144,0.342167,0.378626,0.395976,0.372983,0.336296
78,2098,M01WD2M01WD1M02WD2M02WD1M03WD1M03WD2M04WD2M04W...,NCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP...,ELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCW...,1.0,0.340846,0.340269,0.361091,0.341073,0.384500,0.347698,0.386321,0.402442,0.383587,0.343730
79,2099,M01WD1M01WD2M02WD1M02WD2M03WD2M03WD1M04WD1M04W...,NCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP...,ELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCW...,1.0,0.333671,0.333300,0.371159,0.344234,0.384406,0.350906,0.386540,0.398368,0.382125,0.358120
80,2100,M01WD1M01WD2M02WD1M02WD2M03WD2M03WD1M04WD2M04W...,NCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP_AFNCAP...,ELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCWNFELCW...,1.0,0.352223,0.335945,0.366025,0.327848,0.378686,0.344085,0.381622,0.396381,0.364277,0.350989

In [51]:
# merge the two on the 'Yr' column
test = pd.merge(test, test_sum, on='Yr', how='left')
test.head()

,Yr,TimeSlice,Attribute,PSET_CI,Sum,US_CA_n,US_ME_n,US_MD_n,US_MA_n,US_NJ_n,...,US_CA_n_sum,US_ME_n_sum,US_MD_n_sum,US_MA_n_sum,US_NJ_n_sum,US_NY_n_sum,US_NC_n_sum,US_OH_n_sum,US_RI_n_sum,US_VA_n_sum
0,2020,M01WD1,NCAP_AF,ELCWNF,0.021858,0.006267,0.008229,0.004155,0.004450,0.007751,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.40638,0.369749,0.344388
1,2020,M01WD2,NCAP_AF,ELCWNF,0.062842,0.022322,0.023044,0.020732,0.017409,0.023303,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.40638,0.369749,0.344388
2,2020,M02WD1,NCAP_AF,ELCWNF,0.024590,0.009208,0.009083,0.007060,0.007051,0.009265,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.40638,0.369749,0.344388
3,2020,M02WD2,NCAP_AF,ELCWNF,0.054645,0.017600,0.021644,0.018348,0.016675,0.020909,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.40638,0.369749,0.344388
4,2020,M03WD1,NCAP_AF,ELCWNF,0.024590,0.009375,0.009724,0.009240,0.008164,0.009956,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.40638,0.369749,0.344388

In [52]:
# if the column name ends with '_n', then divide the column by the column with the same name but with '_sum' at the end
for col in test.columns:
    if col.endswith('_n'):
        test[col] = test[col] / test[col + '_sum']
test

,Yr,TimeSlice,Attribute,PSET_CI,Sum,US_CA_n,US_ME_n,US_MD_n,US_MA_n,US_NJ_n,...,US_CA_n_sum,US_ME_n_sum,US_MD_n_sum,US_MA_n_sum,US_NJ_n_sum,US_NY_n_sum,US_NC_n_sum,US_OH_n_sum,US_RI_n_sum,US_VA_n_sum
0,2020,M01WD1,NCAP_AF,ELCWNF,0.021858,0.018269,0.023501,0.011481,0.013015,0.020440,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.406380,0.369749,0.344388
1,2020,M01WD2,NCAP_AF,ELCWNF,0.062842,0.065074,0.065810,0.057285,0.050923,0.061458,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.406380,0.369749,0.344388
2,2020,M02WD1,NCAP_AF,ELCWNF,0.024590,0.026845,0.025939,0.019507,0.020624,0.024434,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.406380,0.369749,0.344388
3,2020,M02WD2,NCAP_AF,ELCWNF,0.054645,0.051309,0.061811,0.050699,0.048777,0.055144,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.406380,0.369749,0.344388
4,2020,M03WD1,NCAP_AF,ELCWNF,0.024590,0.027331,0.027770,0.025533,0.023881,0.026256,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.406380,0.369749,0.344388
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1939,2100,M10WD1,NCAP_AF,ELCWNF,0.024590,0.028308,0.027414,0.026658,0.027445,0.026011,...,0.352223,0.335945,0.366025,0.327848,0.378686,0.344085,0.381622,0.396381,0.364277,0.350989
1940,2100,M11WD1,NCAP_AF,ELCWNF,0.024590,0.024872,0.030501,0.025203,0.021981,0.025486,...,0.352223,0.335945,0.366025,0.327848,0.378686,0.344085,0.381622,0.396381,0.364277,0.350989
1941,2100,M11WD2,NCAP_AF,ELCWNF,0.057377,0.059469,0.065628,0.053214,0.051559,0.055331,...,0.352223,0.335945,0.366025,0.327848,0.378686,0.344085,0.381622,0.396381,0.364277,0.350989
1942,2100,M12WD1,NCAP_AF,ELCWNF,0.021858,0.021271,0.022242,0.020183,0.021620,0.021205,...,0.352223,0.335945,0.366025,0.327848,0.378686,0.344085,0.381622,0.396381,0.364277,0.350989
1943,2100,M12WD2,NCAP_AF,ELCWNF,0.062842,0.064478,0.055331,0.061105,0.063135,0.063290,...,0.352223,0.335945,0.366025,0.327848,0.378686,0.344085,0.381622,0.396381,0.364277,0.350989

In [53]:
test

,Yr,TimeSlice,Attribute,PSET_CI,Sum,US_CA_n,US_ME_n,US_MD_n,US_MA_n,US_NJ_n,...,US_CA_n_sum,US_ME_n_sum,US_MD_n_sum,US_MA_n_sum,US_NJ_n_sum,US_NY_n_sum,US_NC_n_sum,US_OH_n_sum,US_RI_n_sum,US_VA_n_sum
0,2020,M01WD1,NCAP_AF,ELCWNF,0.021858,0.018269,0.023501,0.011481,0.013015,0.020440,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.406380,0.369749,0.344388
1,2020,M01WD2,NCAP_AF,ELCWNF,0.062842,0.065074,0.065810,0.057285,0.050923,0.061458,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.406380,0.369749,0.344388
2,2020,M02WD1,NCAP_AF,ELCWNF,0.024590,0.026845,0.025939,0.019507,0.020624,0.024434,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.406380,0.369749,0.344388
3,2020,M02WD2,NCAP_AF,ELCWNF,0.054645,0.051309,0.061811,0.050699,0.048777,0.055144,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.406380,0.369749,0.344388
4,2020,M03WD1,NCAP_AF,ELCWNF,0.024590,0.027331,0.027770,0.025533,0.023881,0.026256,...,0.343026,0.350155,0.361901,0.341871,0.379177,0.352727,0.380754,0.406380,0.369749,0.344388
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1939,2100,M10WD1,NCAP_AF,ELCWNF,0.024590,0.028308,0.027414,0.026658,0.027445,0.026011,...,0.352223,0.335945,0.366025,0.327848,0.378686,0.344085,0.381622,0.396381,0.364277,0.350989
1940,2100,M11WD1,NCAP_AF,ELCWNF,0.024590,0.024872,0.030501,0.025203,0.021981,0.025486,...,0.352223,0.335945,0.366025,0.327848,0.378686,0.344085,0.381622,0.396381,0.364277,0.350989
1941,2100,M11WD2,NCAP_AF,ELCWNF,0.057377,0.059469,0.065628,0.053214,0.051559,0.055331,...,0.352223,0.335945,0.366025,0.327848,0.378686,0.344085,0.381622,0.396381,0.364277,0.350989
1942,2100,M12WD1,NCAP_AF,ELCWNF,0.021858,0.021271,0.022242,0.020183,0.021620,0.021205,...,0.352223,0.335945,0.366025,0.327848,0.378686,0.344085,0.381622,0.396381,0.364277,0.350989
1943,2100,M12WD2,NCAP_AF,ELCWNF,0.062842,0.064478,0.055331,0.061105,0.063135,0.063290,...,0.352223,0.335945,0.366025,0.327848,0.378686,0.344085,0.381622,0.396381,0.364277,0.350989

In [54]:
# drop all columns that end with '_sum'
test = test.drop(test.filter(regex='_sum$').columns, axis=1)
test

,Yr,TimeSlice,Attribute,PSET_CI,Sum,US_CA_n,US_ME_n,US_MD_n,US_MA_n,US_NJ_n,US_NY_n,US_NC_n,US_OH_n,US_RI_n,US_VA_n
0,2020,M01WD1,NCAP_AF,ELCWNF,0.021858,0.018269,0.023501,0.011481,0.013015,0.020440,0.012718,0.017966,0.017006,0.022796,0.009491
1,2020,M01WD2,NCAP_AF,ELCWNF,0.062842,0.065074,0.065810,0.057285,0.050923,0.061458,0.051607,0.063520,0.052151,0.063228,0.060985
2,2020,M02WD1,NCAP_AF,ELCWNF,0.024590,0.026845,0.025939,0.019507,0.020624,0.024434,0.019968,0.023296,0.022963,0.027972,0.020651
3,2020,M02WD2,NCAP_AF,ELCWNF,0.054645,0.051309,0.061811,0.050699,0.048777,0.055144,0.050070,0.055233,0.059052,0.059413,0.052790
4,2020,M03WD1,NCAP_AF,ELCWNF,0.024590,0.027331,0.027770,0.025533,0.023881,0.026256,0.024194,0.023226,0.021295,0.028573,0.028085
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1939,2100,M10WD1,NCAP_AF,ELCWNF,0.024590,0.028308,0.027414,0.026658,0.027445,0.026011,0.028299,0.024892,0.027409,0.028052,0.025469
1940,2100,M11WD1,NCAP_AF,ELCWNF,0.024590,0.024872,0.030501,0.025203,0.021981,0.025486,0.021914,0.025716,0.026076,0.027480,0.025383
1941,2100,M11WD2,NCAP_AF,ELCWNF,0.057377,0.059469,0.065628,0.053214,0.051559,0.055331,0.051328,0.053230,0.060982,0.059874,0.049709
1942,2100,M12WD1,NCAP_AF,ELCWNF,0.021858,0.021271,0.022242,0.020183,0.021620,0.021205,0.021261,0.019423,0.022731,0.022279,0.019315
1943,2100,M12WD2,NCAP_AF,ELCWNF,0.062842,0.064478,0.055331,0.061105,0.063135,0.063290,0.060679,0.062395,0.060051,0.062378,0.062327

In [55]:
# remove the '_n' from the column names
test.columns = test.columns.str.replace('_n', '')
# drop 
test

,Yr,TimeSlice,Attribute,PSET_CI,Sum,US_CA,US_ME,US_MD,US_MA,US_NJ,US_NY,US_NC,US_OH,US_RI,US_VA
0,2020,M01WD1,NCAP_AF,ELCWNF,0.021858,0.018269,0.023501,0.011481,0.013015,0.020440,0.012718,0.017966,0.017006,0.022796,0.009491
1,2020,M01WD2,NCAP_AF,ELCWNF,0.062842,0.065074,0.065810,0.057285,0.050923,0.061458,0.051607,0.063520,0.052151,0.063228,0.060985
2,2020,M02WD1,NCAP_AF,ELCWNF,0.024590,0.026845,0.025939,0.019507,0.020624,0.024434,0.019968,0.023296,0.022963,0.027972,0.020651
3,2020,M02WD2,NCAP_AF,ELCWNF,0.054645,0.051309,0.061811,0.050699,0.048777,0.055144,0.050070,0.055233,0.059052,0.059413,0.052790
4,2020,M03WD1,NCAP_AF,ELCWNF,0.024590,0.027331,0.027770,0.025533,0.023881,0.026256,0.024194,0.023226,0.021295,0.028573,0.028085
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1939,2100,M10WD1,NCAP_AF,ELCWNF,0.024590,0.028308,0.027414,0.026658,0.027445,0.026011,0.028299,0.024892,0.027409,0.028052,0.025469
1940,2100,M11WD1,NCAP_AF,ELCWNF,0.024590,0.024872,0.030501,0.025203,0.021981,0.025486,0.021914,0.025716,0.026076,0.027480,0.025383
1941,2100,M11WD2,NCAP_AF,ELCWNF,0.057377,0.059469,0.065628,0.053214,0.051559,0.055331,0.051328,0.053230,0.060982,0.059874,0.049709
1942,2100,M12WD1,NCAP_AF,ELCWNF,0.021858,0.021271,0.022242,0.020183,0.021620,0.021205,0.021261,0.019423,0.022731,0.022279,0.019315
1943,2100,M12WD2,NCAP_AF,ELCWNF,0.062842,0.064478,0.055331,0.061105,0.063135,0.063290,0.060679,0.062395,0.060051,0.062378,0.062327

In [56]:
# Replace the values in Attribute with COM_FR
test['Attribute'] = 'COM_FR'
# Replace the column name PSet_CI = Cset_CN 
test = test.rename(columns={'PSet_CI': 'CSet_CN'})
test

,Yr,TimeSlice,Attribute,PSET_CI,Sum,US_CA,US_ME,US_MD,US_MA,US_NJ,US_NY,US_NC,US_OH,US_RI,US_VA
0,2020,M01WD1,COM_FR,ELCWNF,0.021858,0.018269,0.023501,0.011481,0.013015,0.020440,0.012718,0.017966,0.017006,0.022796,0.009491
1,2020,M01WD2,COM_FR,ELCWNF,0.062842,0.065074,0.065810,0.057285,0.050923,0.061458,0.051607,0.063520,0.052151,0.063228,0.060985
2,2020,M02WD1,COM_FR,ELCWNF,0.024590,0.026845,0.025939,0.019507,0.020624,0.024434,0.019968,0.023296,0.022963,0.027972,0.020651
3,2020,M02WD2,COM_FR,ELCWNF,0.054645,0.051309,0.061811,0.050699,0.048777,0.055144,0.050070,0.055233,0.059052,0.059413,0.052790
4,2020,M03WD1,COM_FR,ELCWNF,0.024590,0.027331,0.027770,0.025533,0.023881,0.026256,0.024194,0.023226,0.021295,0.028573,0.028085
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1939,2100,M10WD1,COM_FR,ELCWNF,0.024590,0.028308,0.027414,0.026658,0.027445,0.026011,0.028299,0.024892,0.027409,0.028052,0.025469
1940,2100,M11WD1,COM_FR,ELCWNF,0.024590,0.024872,0.030501,0.025203,0.021981,0.025486,0.021914,0.025716,0.026076,0.027480,0.025383
1941,2100,M11WD2,COM_FR,ELCWNF,0.057377,0.059469,0.065628,0.053214,0.051559,0.055331,0.051328,0.053230,0.060982,0.059874,0.049709
1942,2100,M12WD1,COM_FR,ELCWNF,0.021858,0.021271,0.022242,0.020183,0.021620,0.021205,0.021261,0.019423,0.022731,0.022279,0.019315
1943,2100,M12WD2,COM_FR,ELCWNF,0.062842,0.064478,0.055331,0.061105,0.063135,0.063290,0.060679,0.062395,0.060051,0.062378,0.062327

In [57]:
# Drop the 'Sum' column
test = test.drop('Sum', axis=1)
test

,Yr,TimeSlice,Attribute,PSET_CI,US_CA,US_ME,US_MD,US_MA,US_NJ,US_NY,US_NC,US_OH,US_RI,US_VA
0,2020,M01WD1,COM_FR,ELCWNF,0.018269,0.023501,0.011481,0.013015,0.020440,0.012718,0.017966,0.017006,0.022796,0.009491
1,2020,M01WD2,COM_FR,ELCWNF,0.065074,0.065810,0.057285,0.050923,0.061458,0.051607,0.063520,0.052151,0.063228,0.060985
2,2020,M02WD1,COM_FR,ELCWNF,0.026845,0.025939,0.019507,0.020624,0.024434,0.019968,0.023296,0.022963,0.027972,0.020651
3,2020,M02WD2,COM_FR,ELCWNF,0.051309,0.061811,0.050699,0.048777,0.055144,0.050070,0.055233,0.059052,0.059413,0.052790
4,2020,M03WD1,COM_FR,ELCWNF,0.027331,0.027770,0.025533,0.023881,0.026256,0.024194,0.023226,0.021295,0.028573,0.028085
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1939,2100,M10WD1,COM_FR,ELCWNF,0.028308,0.027414,0.026658,0.027445,0.026011,0.028299,0.024892,0.027409,0.028052,0.025469
1940,2100,M11WD1,COM_FR,ELCWNF,0.024872,0.030501,0.025203,0.021981,0.025486,0.021914,0.025716,0.026076,0.027480,0.025383
1941,2100,M11WD2,COM_FR,ELCWNF,0.059469,0.065628,0.053214,0.051559,0.055331,0.051328,0.053230,0.060982,0.059874,0.049709
1942,2100,M12WD1,COM_FR,ELCWNF,0.021271,0.022242,0.020183,0.021620,0.021205,0.021261,0.019423,0.022731,0.022279,0.019315
1943,2100,M12WD2,COM_FR,ELCWNF,0.064478,0.055331,0.061105,0.063135,0.063290,0.060679,0.062395,0.060051,0.062378,0.062327

In [58]:
# save to excel as 'SSP126_projectedstatus_usa_onshore_TUSM_TS40_NEWVERSION.excel'
test.to_excel('SSP126_projectedstatus_usa_offshore_TUSM_TS120_NEWVERSION.xlsx')

8760 Method for COM_FR

This is the same as earlier in the code, however, there is no timeslice weighting, so divide the CF by the annual sum

In [1]:
import pandas as pd
test = pd.read_excel('SSP126_projectedstatus_usa_offshore_TS8760_TUSM.xlsx')
test

,TimeSlice,Yr,Month,Day,time,Attribute,PSET_CI,US_CA,US_ME,US_MD,US_MA,US_NJ,US_NY,US_NC,US_OH,US_RI,US_VA,Season,Weekday,Type
0,M01D01,2020,1,1,2020-01-01T00:00:00.000000,NCAP_AF,ELCWNF,0.367714,0.193936,0.474780,0.454732,0.402930,0.410780,0.468683,0.359083,0.379232,0.466300,S01,3,WD2
1,M01D02,2020,1,2,2020-01-02T00:00:00.000000,NCAP_AF,ELCWNF,0.445264,0.193936,0.429447,0.449118,0.408255,0.449919,0.443601,0.471457,0.331932,0.450326,S01,4,WD2
2,M01D03,2020,1,3,2020-01-03T00:00:00.000000,NCAP_AF,ELCWNF,0.331309,0.421845,0.273422,0.278977,0.370705,0.238053,0.293852,0.359083,0.421845,0.151292,S01,5,WD2
3,M01D04,2020,1,4,2020-01-04T00:00:00.000000,NCAP_AF,ELCWNF,0.402844,0.438555,0.076408,0.082135,0.290840,0.099952,0.282556,0.059775,0.444439,0.090205,S01,6,WD2
4,M01D05,2020,1,5,2020-01-05T00:00:00.000000,NCAP_AF,ELCWNF,0.164764,0.452113,0.080716,0.076816,0.292951,0.100352,0.288809,0.226102,0.432351,0.090205,S01,7,WD1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29580,M12D27,2100,12,27,2100-12-27T00:00:00.000000,NCAP_AF,ELCWNF,0.340483,0.421845,0.476976,0.448348,0.283607,0.457793,0.162758,0.455180,0.379232,0.388957,S01,1,WD1
29581,M12D28,2100,12,28,2100-12-28T00:00:00.000000,NCAP_AF,ELCWNF,0.302823,0.000000,0.305742,0.250720,0.373851,0.269423,0.375552,0.350062,0.436877,0.314227,S01,2,WD2
29582,M12D29,2100,12,29,2100-12-29T00:00:00.000000,NCAP_AF,ELCWNF,0.382784,0.449057,0.450714,0.151811,0.398974,0.246326,0.461007,0.436877,0.449057,0.471723,S01,3,WD2
29583,M12D30,2100,12,30,2100-12-30T00:00:00.000000,NCAP_AF,ELCWNF,0.402710,0.000000,0.426296,0.464709,0.410062,0.461738,0.379333,0.350062,0.379232,0.314227,S01,4,WD2
29584,M12D31,2100,12,31,2100-12-31T00:00:00.000000,NCAP_AF,ELCWNF,0.430200,0.000000,0.337667,0.448348,0.385972,0.412492,0.297252,0.384675,0.379232,0.353232,S01,5,WD2

In [2]:
# List of US_* column names
us_columns = [col for col in test.columns if col.startswith('US_')]

# rename us_columns by adding _n to the end of each column name in us_columns. remove the us_columns from test
test = test.rename(columns={col: col + '_n' for col in us_columns})
test

,TimeSlice,Yr,Month,Day,time,Attribute,PSET_CI,US_CA_n,US_ME_n,US_MD_n,US_MA_n,US_NJ_n,US_NY_n,US_NC_n,US_OH_n,US_RI_n,US_VA_n,Season,Weekday,Type
0,M01D01,2020,1,1,2020-01-01T00:00:00.000000,NCAP_AF,ELCWNF,0.367714,0.193936,0.474780,0.454732,0.402930,0.410780,0.468683,0.359083,0.379232,0.466300,S01,3,WD2
1,M01D02,2020,1,2,2020-01-02T00:00:00.000000,NCAP_AF,ELCWNF,0.445264,0.193936,0.429447,0.449118,0.408255,0.449919,0.443601,0.471457,0.331932,0.450326,S01,4,WD2
2,M01D03,2020,1,3,2020-01-03T00:00:00.000000,NCAP_AF,ELCWNF,0.331309,0.421845,0.273422,0.278977,0.370705,0.238053,0.293852,0.359083,0.421845,0.151292,S01,5,WD2
3,M01D04,2020,1,4,2020-01-04T00:00:00.000000,NCAP_AF,ELCWNF,0.402844,0.438555,0.076408,0.082135,0.290840,0.099952,0.282556,0.059775,0.444439,0.090205,S01,6,WD2
4,M01D05,2020,1,5,2020-01-05T00:00:00.000000,NCAP_AF,ELCWNF,0.164764,0.452113,0.080716,0.076816,0.292951,0.100352,0.288809,0.226102,0.432351,0.090205,S01,7,WD1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29580,M12D27,2100,12,27,2100-12-27T00:00:00.000000,NCAP_AF,ELCWNF,0.340483,0.421845,0.476976,0.448348,0.283607,0.457793,0.162758,0.455180,0.379232,0.388957,S01,1,WD1
29581,M12D28,2100,12,28,2100-12-28T00:00:00.000000,NCAP_AF,ELCWNF,0.302823,0.000000,0.305742,0.250720,0.373851,0.269423,0.375552,0.350062,0.436877,0.314227,S01,2,WD2
29582,M12D29,2100,12,29,2100-12-29T00:00:00.000000,NCAP_AF,ELCWNF,0.382784,0.449057,0.450714,0.151811,0.398974,0.246326,0.461007,0.436877,0.449057,0.471723,S01,3,WD2
29583,M12D30,2100,12,30,2100-12-30T00:00:00.000000,NCAP_AF,ELCWNF,0.402710,0.000000,0.426296,0.464709,0.410062,0.461738,0.379333,0.350062,0.379232,0.314227,S01,4,WD2
29584,M12D31,2100,12,31,2100-12-31T00:00:00.000000,NCAP_AF,ELCWNF,0.430200,0.000000,0.337667,0.448348,0.385972,0.412492,0.297252,0.384675,0.379232,0.353232,S01,5,WD2

In [3]:
# group by Year and find the sum of each column, rename each column with '_sum' at the end
test_sum = test.groupby('Yr').sum().add_suffix('_sum').reset_index()

In [4]:
# merge the two on the 'Yr' column
test = pd.merge(test, test_sum, on='Yr', how='left')
test.head()

,TimeSlice,Yr,Month,Day,time,Attribute,PSET_CI,US_CA_n,US_ME_n,US_MD_n,...,US_MA_n_sum,US_NJ_n_sum,US_NY_n_sum,US_NC_n_sum,US_OH_n_sum,US_RI_n_sum,US_VA_n_sum,Season_sum,Weekday_sum,Type_sum
0,M01D01,2020,1,1,2020-01-01T00:00:00.000000,NCAP_AF,ELCWNF,0.367714,0.193936,0.474780,...,124.994261,138.87288,129.02502,139.388279,148.494238,135.410606,126.0857,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1463,WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2W...
1,M01D02,2020,1,2,2020-01-02T00:00:00.000000,NCAP_AF,ELCWNF,0.445264,0.193936,0.429447,...,124.994261,138.87288,129.02502,139.388279,148.494238,135.410606,126.0857,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1463,WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2W...
2,M01D03,2020,1,3,2020-01-03T00:00:00.000000,NCAP_AF,ELCWNF,0.331309,0.421845,0.273422,...,124.994261,138.87288,129.02502,139.388279,148.494238,135.410606,126.0857,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1463,WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2W...
3,M01D04,2020,1,4,2020-01-04T00:00:00.000000,NCAP_AF,ELCWNF,0.402844,0.438555,0.076408,...,124.994261,138.87288,129.02502,139.388279,148.494238,135.410606,126.0857,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1463,WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2W...
4,M01D05,2020,1,5,2020-01-05T00:00:00.000000,NCAP_AF,ELCWNF,0.164764,0.452113,0.080716,...,124.994261,138.87288,129.02502,139.388279,148.494238,135.410606,126.0857,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1463,WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2W...

In [5]:
# if the column name ends with '_n', then divide the column by the column with the same name but with '_sum' at the end
for col in test.columns:
    if col.endswith('_n'):
        test[col] = test[col] / test[col + '_sum']
test

,TimeSlice,Yr,Month,Day,time,Attribute,PSET_CI,US_CA_n,US_ME_n,US_MD_n,...,US_MA_n_sum,US_NJ_n_sum,US_NY_n_sum,US_NC_n_sum,US_OH_n_sum,US_RI_n_sum,US_VA_n_sum,Season_sum,Weekday_sum,Type_sum
0,M01D01,2020,1,1,2020-01-01T00:00:00.000000,NCAP_AF,ELCWNF,0.002929,0.001513,0.003586,...,124.994261,138.872880,129.025020,139.388279,148.494238,135.410606,126.085700,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1463,WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2W...
1,M01D02,2020,1,2,2020-01-02T00:00:00.000000,NCAP_AF,ELCWNF,0.003547,0.001513,0.003244,...,124.994261,138.872880,129.025020,139.388279,148.494238,135.410606,126.085700,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1463,WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2W...
2,M01D03,2020,1,3,2020-01-03T00:00:00.000000,NCAP_AF,ELCWNF,0.002639,0.003290,0.002065,...,124.994261,138.872880,129.025020,139.388279,148.494238,135.410606,126.085700,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1463,WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2W...
3,M01D04,2020,1,4,2020-01-04T00:00:00.000000,NCAP_AF,ELCWNF,0.003209,0.003421,0.000577,...,124.994261,138.872880,129.025020,139.388279,148.494238,135.410606,126.085700,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1463,WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2W...
4,M01D05,2020,1,5,2020-01-05T00:00:00.000000,NCAP_AF,ELCWNF,0.001313,0.003526,0.000610,...,124.994261,138.872880,129.025020,139.388279,148.494238,135.410606,126.085700,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1463,WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2W...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29580,M12D27,2100,12,27,2100-12-27T00:00:00.000000,NCAP_AF,ELCWNF,0.002649,0.003437,0.003572,...,119.572123,138.209974,125.522649,139.238181,144.726845,133.036323,128.008673,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1461,WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2W...
29581,M12D28,2100,12,28,2100-12-28T00:00:00.000000,NCAP_AF,ELCWNF,0.002356,0.000000,0.002290,...,119.572123,138.209974,125.522649,139.238181,144.726845,133.036323,128.008673,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1461,WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2W...
29582,M12D29,2100,12,29,2100-12-29T00:00:00.000000,NCAP_AF,ELCWNF,0.002978,0.003659,0.003375,...,119.572123,138.209974,125.522649,139.238181,144.726845,133.036323,128.008673,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1461,WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2W...
29583,M12D30,2100,12,30,2100-12-30T00:00:00.000000,NCAP_AF,ELCWNF,0.003133,0.000000,0.003193,...,119.572123,138.209974,125.522649,139.238181,144.726845,133.036323,128.008673,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1461,WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2W...
29584,M12D31,2100,12,31,2100-12-31T00:00:00.000000,NCAP_AF,ELCWNF,0.003347,0.000000,0.002529,...,119.572123,138.209974,125.522649,139.238181,144.726845,133.036323,128.008673,S01S01S01S01S01S01S01S01S01S01S01S01S01S01S01S...,1461,WD2WD2WD1WD1WD2WD2WD2WD2WD2WD1WD1WD2WD2WD2WD2W...

In [6]:
# drop all columns that end with '_sum'
test = test.drop(test.filter(regex='_sum$').columns, axis=1)
# remove the '_n' from the column names
test.columns = test.columns.str.replace('_n', '')
# Replace the values in Attribute with COM_FR
test['Attribute'] = 'COM_FR'
# Replace the column name PSet_CI = Cset_CN 
test = test.rename(columns={'PSet_CI': 'CSet_CN'})

In [7]:
# drop Month, Day, time, Season, Weekday, and Type columns
test = test.drop(['Month', 'Day', 'time', 'Season', 'Weekday', 'Type'], axis=1)

In [8]:
test

,TimeSlice,Yr,Attribute,PSET_CI,US_CA,US_ME,US_MD,US_MA,US_NJ,US_NY,US_NC,US_OH,US_RI,US_VA
0,M01D01,2020,COM_FR,ELCWNF,0.002929,0.001513,0.003586,0.003638,0.002901,0.003184,0.003362,0.002418,0.002801,0.003698
1,M01D02,2020,COM_FR,ELCWNF,0.003547,0.001513,0.003244,0.003593,0.002940,0.003487,0.003182,0.003175,0.002451,0.003572
2,M01D03,2020,COM_FR,ELCWNF,0.002639,0.003290,0.002065,0.002232,0.002669,0.001845,0.002108,0.002418,0.003115,0.001200
3,M01D04,2020,COM_FR,ELCWNF,0.003209,0.003421,0.000577,0.000657,0.002094,0.000775,0.002027,0.000403,0.003282,0.000715
4,M01D05,2020,COM_FR,ELCWNF,0.001313,0.003526,0.000610,0.000615,0.002109,0.000778,0.002072,0.001523,0.003193,0.000715
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29580,M12D27,2100,COM_FR,ELCWNF,0.002649,0.003437,0.003572,0.003750,0.002052,0.003647,0.001169,0.003145,0.002851,0.003039
29581,M12D28,2100,COM_FR,ELCWNF,0.002356,0.000000,0.002290,0.002097,0.002705,0.002146,0.002697,0.002419,0.003284,0.002455
29582,M12D29,2100,COM_FR,ELCWNF,0.002978,0.003659,0.003375,0.001270,0.002887,0.001962,0.003311,0.003019,0.003375,0.003685
29583,M12D30,2100,COM_FR,ELCWNF,0.003133,0.000000,0.003193,0.003886,0.002967,0.003679,0.002724,0.002419,0.002851,0.002455
29584,M12D31,2100,COM_FR,ELCWNF,0.003347,0.000000,0.002529,0.003750,0.002793,0.003286,0.002135,0.002658,0.002851,0.002759

In [9]:
# save to excel as 'SSP126_projectedstatus_usa_onshore_TUSM_TS8760_NEWVERSION.excel'
test.to_excel('SSP126_projectedstatus_usa_offshore_TUSM_TS8760_NEWVERSION.xlsx')