## Import Packages

In [2]:
import xarray as xr
import pandas as pd
import numpy as np
import holoviews as hv
from holoviews import opts
import dask.dataframe as dd
import hvplot.dask  # noqa

import numpy as np
import holoviews as hv
import pandas as pd
import numpy as np

import polars as pl

hv.extension('bokeh')

# Import Data

In [94]:
# 25 MB chunks 

df15 = dd.read_csv('ssp126_usa_onshore_daily_2015_2020.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df21 = dd.read_csv('ssp126_usa_onshore_daily_2021_2030.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df31 = dd.read_csv('ssp126_usa_onshore_daily_2031_2040.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df41 = dd.read_csv('ssp126_usa_onshore_daily_2041_2050.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df51 = dd.read_csv('ssp126_usa_onshore_daily_2051_2060.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df61 = dd.read_csv('ssp126_usa_onshore_daily_2061_2070.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df71 = dd.read_csv('ssp126_usa_onshore_daily_2071_2080.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df81 = dd.read_csv('ssp126_usa_onshore_daily_2081_2090.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})
df91 = dd.read_csv('ssp126_usa_onshore_daily_2091_2100.csv', blocksize=25e6, dtype={'lat': 'float64','lon': 'float64','sfcwind': 'float64','Capacity (MW)': 'float64', 'City' : 'string','Local area (taluk, county)' :'string','Major area (prefecture, district)':'string', 'State/Province':'string', 'Region':'string','Country':'string','sfc_wind80m':'float64','sfc_wind80m_floor':'float64'})

In [95]:
# merge dask dataframe to pandas dataframe
import dask.dataframe as dd
join = dd.concat([df15, df21])
join2 = dd.concat([join, df31])
join3 = dd.concat([join2, df41])
join4 = dd.concat([join3, df51])
join5 = dd.concat([join4, df61])
join6 = dd.concat([join5, df71])
join7 = dd.concat([join6, df81])
SSP126 = dd.concat([join7, df91])

# inspect results
# join.compute()

In [96]:
SSP126.tail()

,index,time,lat,lon,sfcwind,Capacity (MW),City,"Local area (taluk, county)","Major area (prefecture, district)",State/Province,Region,Country,sfc_wind80m,sfc_wind80m_floor
214646,23129,2100-12-27,42.75,-115.25,2.856540,21.0,<NA>,Twin Falls County,<NA>,Idaho,Americas,United States,3.845760,3.5
214647,23129,2100-12-28,42.75,-115.25,5.148798,21.0,<NA>,Twin Falls County,<NA>,Idaho,Americas,United States,6.931828,6.5
214648,23129,2100-12-29,42.75,-115.25,1.836774,21.0,<NA>,Twin Falls County,<NA>,Idaho,Americas,United States,2.472850,2.0
214649,23129,2100-12-30,42.75,-115.25,2.164511,21.0,<NA>,Twin Falls County,<NA>,Idaho,Americas,United States,2.914081,2.5
214650,23129,2100-12-31,42.75,-115.25,4.175478,21.0,<NA>,Twin Falls County,<NA>,Idaho,Americas,United States,5.621446,5.5

In [97]:
SSP126['Year'] = SSP126['time'].astype(str).str[:4] # creating year column
SSP126['Year'] = SSP126['Year'].astype(int) 
# add a column that is called 'loc' and it is the combination of lat and lon with a comma in between
SSP126['loc'] = SSP126['lat'].astype(str) + ',' + SSP126['lon'].astype(str)
SSP126.head()

,index,time,lat,lon,sfcwind,Capacity (MW),City,"Local area (taluk, county)","Major area (prefecture, district)",State/Province,Region,Country,sfc_wind80m,sfc_wind80m_floor,Year,loc
0,21508,2015-01-01,41.75,-93.75,3.373440,30.0,<NA>,Boone County,<NA>,Iowa,Americas,United States,4.541662,4.5,2015,"41.75,-93.75"
1,21508,2015-01-02,41.75,-93.75,3.341947,30.0,<NA>,Boone County,<NA>,Iowa,Americas,United States,4.499263,4.0,2015,"41.75,-93.75"
2,21508,2015-01-03,41.75,-93.75,3.919792,30.0,<NA>,Boone County,<NA>,Iowa,Americas,United States,5.277217,5.0,2015,"41.75,-93.75"
3,21508,2015-01-04,41.75,-93.75,2.496856,30.0,<NA>,Boone County,<NA>,Iowa,Americas,United States,3.361518,3.0,2015,"41.75,-93.75"
4,21508,2015-01-05,41.75,-93.75,4.605200,30.0,<NA>,Boone County,<NA>,Iowa,Americas,United States,6.199982,6.0,2015,"41.75,-93.75"

In [98]:
# split the 'SSP126' into datasets with the following years: 2015-2039, 2040-2064, 2065-2089, 2090-2100
SSP126_2015_2039 = SSP126[SSP126['Year'] <= 2039]
SSP126_2040_2064 = SSP126[(SSP126['Year'] >= 2040) & (SSP126['Year'] <= 2064)]
SSP126_2065_2089 = SSP126[(SSP126['Year'] >= 2065) & (SSP126['Year'] <= 2089)]
SSP126_2090_2100 = SSP126[SSP126['Year'] >= 2090]

Apply IEC Class

In [99]:
#group by loc and find the mean sfc_wind80m_floor. Uncomment and run one at a time. this takes a long time


SSP126_2015_2039_iec = SSP126_2015_2039.groupby('loc')['sfc_wind80m_floor'].mean().compute()
SSP126_2040_2064_iec = SSP126_2040_2064.groupby('loc')['sfc_wind80m_floor'].mean().compute()
SSP126_2065_2089_iec = SSP126_2065_2089.groupby('loc')['sfc_wind80m_floor'].mean().compute()
SSP126_2090_2100_iec = SSP126_2090_2100.groupby('loc')['sfc_wind80m_floor'].mean().compute()

In [100]:
SSP126_2015_2039_iec

loc
20.75,-156.25    7.700854
27.25,-97.25     5.931059
29.25,-100.25    5.021958
31.75,-100.75    5.962107
31.75,-101.75    6.029898
                   ...
45.25,-119.75    4.032417
46.25,-118.25    3.576169
46.75,-120.25    2.878765
47.25,-120.25    2.744716
48.25,-100.75    5.380079
Name: sfc_wind80m_floor, Length: 444, dtype: float64

In [101]:
def IEC_Class(s): # s being sfc_wind80m_foor  25-year avg 
    if s < 7.5:
        return 1
    elif  7.5 <= s <= 8.5:
        return 2
    elif s > 8.5:
        return 3

In [102]:
#apply the IEC_Class function to the mean sfc_wind80m_floor in SSP126_2015_2039_iec and name the column 'iec'. Uncomment and run one at a time

SSP126_2015_2039_iec_n = SSP126_2015_2039_iec.apply(IEC_Class).rename('iec')
SSP126_2040_2064_iec_n = SSP126_2040_2064_iec.apply(IEC_Class).rename('iec')
SSP126_2065_2089_iec_n = SSP126_2065_2089_iec.apply(IEC_Class).rename('iec')
SSP126_2090_2100_iec_n = SSP126_2090_2100_iec.apply(IEC_Class).rename('iec')

In [103]:
# merge the two dataframes on loc. Uncomment and run one at a time
 
SSP126_2015_2039 = dd.merge(SSP126_2015_2039, SSP126_2015_2039_iec_n, on='loc', how='left')
SSP126_2040_2064 = dd.merge(SSP126_2040_2064, SSP126_2040_2064_iec_n, on='loc', how='left')
SSP126_2065_2089 = dd.merge(SSP126_2065_2089, SSP126_2065_2089_iec_n, on='loc', how='left')
SSP126_2090_2100 = dd.merge(SSP126_2090_2100, SSP126_2090_2100_iec_n, on='loc', how='left')

In [104]:
#rename 'sfc_wind80m_floor_x' to 'sfc_wind80m_floor'. Uncomment and run one at a time
SSP126_2015_2039 = SSP126_2015_2039.rename(columns={'sfc_wind80m_floor_x': 'sfc_wind80m_floor'})
SSP126_2040_2064 = SSP126_2040_2064.rename(columns={'sfc_wind80m_floor_x': 'sfc_wind80m_floor'})
SSP126_2065_2089 = SSP126_2065_2089.rename(columns={'sfc_wind80m_floor_x': 'sfc_wind80m_floor'})
SSP126_2090_2100 = SSP126_2090_2100.rename(columns={'sfc_wind80m_floor_x': 'sfc_wind80m_floor'})

In [105]:
IEC_Classifications = dd.read_csv('iec_classifications.csv')
# convert IEC_Class to i64
IEC_Classifications.compute()

     iec  CP_whole  sfc_wind80m_floor  Unnamed: 3        CP
0      1   19.3936                3.0         NaN  0.193936
1      1   33.1932                3.5         NaN  0.331932
2      1   37.9232                4.0         NaN  0.379232
3      1   41.4574                4.5         NaN  0.414574
4      1   42.1845                5.0         NaN  0.421845
..   ...       ...                ...         ...       ...
130    3    1.8872               23.0         NaN  0.018872
131    3    1.6623               23.5         NaN  0.016623
132    3    1.4601               24.0         NaN  0.014601
133    3    1.2781               24.5         NaN  0.012781
134    3    1.1140               25.0         NaN  0.011140

[135 rows x 5 columns]

Now we apply the Capacity Factors to each unique IEC Class

In [106]:
# merge the data on 'iec' and 'sfc_wind80m'. Uncomment and run one at a time
SSP126_2015_2039_n = dd.merge(SSP126_2015_2039, IEC_Classifications, on=['iec', 'sfc_wind80m_floor'], how='left')
SSP126_2040_2064_n = dd.merge(SSP126_2040_2064, IEC_Classifications, on=['iec', 'sfc_wind80m_floor'], how='left')
SSP126_2065_2089_n = dd.merge(SSP126_2065_2089, IEC_Classifications, on=['iec', 'sfc_wind80m_floor'], how='left')
SSP126_2090_2100_n = dd.merge(SSP126_2090_2100, IEC_Classifications, on=['iec', 'sfc_wind80m_floor'], how='left')

In [107]:
# average the CP by TEMELE_REGIONS_COPY and time. Uncomment and run one at a time. this takes a long time
SSP126_2015_2039_tt = SSP126_2015_2039_n.groupby(['State/Province', 'time'])['CP', 'Capacity (MW)'].mean().compute()
SSP126_2040_2064_tt = SSP126_2040_2064_n.groupby(['State/Province', 'time'])['CP', 'Capacity (MW)'].mean().compute()
SSP126_2065_2089_tt = SSP126_2065_2089_n.groupby(['State/Province', 'time'])['CP', 'Capacity (MW)'].mean().compute()
SSP126_2090_2100_tt = SSP126_2090_2100_n.groupby(['State/Province', 'time'])['CP', 'Capacity (MW)'].mean().compute()

In [108]:
SSP126_2015_2039_tt.head()

                                 CP  Capacity (MW)
State/Province time
California     2015-01-01  0.193936      74.433735
               2015-01-02  0.203793      74.433735
               2015-01-03  0.193936      74.433735
               2015-01-04  0.193936      74.433735
               2015-01-05       NaN      74.433735

In [110]:
#save to csv. Uncomment and run one at a time

SSP126_2015_2039_tt.to_csv('SSP126_usa_onshore_2015_2039_test_state.csv')
SSP126_2040_2064_tt.to_csv('SSP126_usa_onshore_2040_2064_test_state.csv')
SSP126_2065_2089_tt.to_csv('SSP126_usa_onshore_2065_2089_test_state.csv')
SSP126_2090_2100_tt.to_csv('SSP126_usa_onshore_2090_2100_test_state.csv')

Organize in the Format that is compliant with TIMES/VEDA 2.0 --> Only Run the Block associated with the proper SSP

In [111]:
# dask open csv
SSP126_2015_2039_tt = dd.read_csv('SSP126_usa_onshore_2015_2039_test_state.csv')
SSP126_2040_2064_tt = dd.read_csv('SSP126_usa_onshore_2040_2064_test_state.csv')
SSP126_2065_2089_tt = dd.read_csv('SSP126_usa_onshore_2065_2089_test_state.csv')
SSP126_2090_2100_tt = dd.read_csv('SSP126_usa_onshore_2090_2100_test_state.csv')

# 2015-2039

In [112]:
#   SSP 126 2015-2039
#create a new column called 'Month' that is the month of the 'time' column
SSP126_2015_2039_tt['Month'] = SSP126_2015_2039_tt['time'].astype(str).str[5:7]
#create a new column called 'Day' that is the day of the 'time' column
SSP126_2015_2039_tt['Day'] = SSP126_2015_2039_tt['time'].astype(str).str[8:10]
#create a new column called 'TimeSlice' that is 'M' + Month + 'D' + Day
SSP126_2015_2039_tt['TimeSlice'] = 'M' + SSP126_2015_2039_tt['Month'] + 'D' + SSP126_2015_2039_tt['Day']
# add a new column called 'Attribute' that is entirely full of 'RNW'
SSP126_2015_2039_tt['Attribute'] = 'NCAP_AF'
# add a new column called 'Yr' that is the year of the 'time' column
SSP126_2015_2039_tt['Yr'] = SSP126_2015_2039_tt['time'].astype(str).str[:4]
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_2015_2039_tt['PSET_CI'] = 'ELCWNO'

SSP126_2015_2039_tt= SSP126_2015_2039_tt.groupby(['State/Province', 'time']).first().compute()
#pivot the table so that TEMELE_REGIONS_COPY are the columns, TimeSlice are the rows, and the values are the CP
SSP126_2015_2039_tt = SSP126_2015_2039_tt.pivot_table(index=['TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI'], columns='State/Province', values='CP', aggfunc='first')
#replace all NaN values with 0
SSP126_2015_2039_tt = SSP126_2015_2039_tt.fillna(0)
# only keep TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI', 'Virginia', 'Rhode Island'
#SSP126_2015_2039_tt = SSP126_2015_2039_tt[['Virginia', 'Rhode Island']]
SSP126_2015_2039_tt

State/Province                                           Alaska   Arizona  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO   0.379232  0.193936
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO   0.286584  0.376895
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO   0.331932  0.331932
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO   0.379232  0.396230
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO   0.000000  0.397226
...                                                         ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO   0.000000  0.000000
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO   0.193936  0.418291
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO   0.379232  0.000000
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO   0.000000  0.323956
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO   0.193936  0.000000

State/Province                                         California  Colorado  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO     0.193936  0.323123
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO     0.219048  0.370889
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO     0.255046  0.438801
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO     0.193936  0.443643
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO     0.207171  0.432455
...                                                           ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO     0.331932  0.415058
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO     0.335349  0.440530
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO     0.000000  0.254597
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO     0.291212  0.422562
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO     0.000000  0.308085

State/Province                                           Hawaii     Idaho  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO   0.364480  0.262934
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO   0.312216  0.371316
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO   0.460097  0.308381
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO   0.364692  0.378624
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO   0.390575  0.380502
...                                                         ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO   0.425731  0.247601
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO   0.376312  0.000000
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO   0.366463  0.262934
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO   0.326631  0.193936
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO   0.403689  0.193936

State/Province                                         Illinois   Indiana  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO   0.408622  0.438507
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO   0.418824  0.407506
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO   0.259675  0.233165
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO   0.306546  0.379232
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO   0.437802  0.440924
...                                                         ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO   0.385002  0.394659
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO   0.371510  0.331932
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO   0.435377  0.421118
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO   0.347292  0.393498
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO   0.416672  0.403971

State/Province                                             Iowa    Kansas  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO   0.407559  0.247011
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO   0.441477  0.442430
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO   0.415686  0.360897
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO   0.345752  0.443008
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO   0.448702  0.406930
...                                                         ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO   0.450977  0.408471
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO   0.404087  0.424088
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO   0.453987  0.387900
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO   0.424078  0.433525
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO   0.441681  0.423761

State/Province                                         ...  Pennsylvania  \
TimeSlice Yr   Month Day time       Attribute PSET_CI  ...
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO   ...      0.446651
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO   ...      0.239935
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO   ...      0.432166
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO   ...      0.242493
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO   ...      0.432013
...                                                    ...           ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO   ...      0.415749
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO   ...      0.311066
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO   ...      0.193936
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO   ...      0.229420
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO   ...      0.446542

State/Province                                         South Dakota  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO       0.432467
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO       0.420918
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO       0.427400
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO       0.416339
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO       0.446905
...                                                             ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO       0.446556
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO       0.442596
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO       0.447026
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO       0.449250
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO       0.411536

State/Province                                         Tennessee     Texas  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO    0.193936  0.389059
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO    0.000000  0.446820
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO    0.193936  0.443481
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO    0.000000  0.445161
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO    0.000000  0.356470
...                                                          ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO    0.448366  0.417587
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO    0.000000  0.415427
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO    0.414574  0.397693
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO    0.000000  0.428208
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO    0.000000  0.448570

State/Province                                             Utah   Vermont  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO   0.193936  0.448366
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO   0.000000  0.309258
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO   0.193936  0.438555
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO   0.347699  0.343757
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO   0.193936  0.420027
...                                                         ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO   0.000000  0.343757
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO   0.193936  0.343757
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO   0.000000  0.000000
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO   0.421845  0.445913
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO   0.000000  0.456123

State/Province                                         Washington  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO     0.331932
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO     0.434237
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO     0.414574
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO     0.420691
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO     0.213650
...                                                           ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO     0.000000
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO     0.361299
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO     0.000000
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO     0.267028
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO     0.331932

State/Province                                         West Virginia  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO        0.446197
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO        0.193936
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO        0.406720
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO        0.193936
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO        0.440857
...                                                              ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO        0.433085
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO        0.327544
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO        0.275248
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO        0.355582
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO        0.427109

State/Province                                         Wisconsin   Wyoming
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2015 01    01  2015-01-01 NCAP_AF   ELCWNO    0.400594  0.446133
          2016 01    01  2016-01-01 NCAP_AF   ELCWNO    0.406202  0.403886
          2017 01    01  2017-01-01 NCAP_AF   ELCWNO    0.395606  0.437235
          2018 01    01  2018-01-01 NCAP_AF   ELCWNO    0.311068  0.431234
          2019 01    01  2019-01-01 NCAP_AF   ELCWNO    0.443935  0.425597
...                                                          ...       ...
M12D31    2035 12    31  2035-12-31 NCAP_AF   ELCWNO    0.435475  0.440800
          2036 12    31  2036-12-31 NCAP_AF   ELCWNO    0.381102  0.410039
          2037 12    31  2037-12-31 NCAP_AF   ELCWNO    0.432802  0.421191
          2038 12    31  2038-12-31 NCAP_AF   ELCWNO    0.410651  0.367515
          2039 12    31  2039-12-31 NCAP_AF   ELCWNO    0.354386  0.407745

[9131 rows x 37 columns]

In [113]:
#export to csv
SSP126_2015_2039_tt.to_csv('SSP126_usa_onshore_2015_2039_TIMES_state.csv')

# 2040-2064

In [114]:
#create a new column called 'Month' that is the month of the 'time' column
SSP126_2040_2064_tt['Month'] = SSP126_2040_2064_tt['time'].astype(str).str[5:7]
#create a new column called 'Day' that is the day of the 'time' column
SSP126_2040_2064_tt['Day'] = SSP126_2040_2064_tt['time'].astype(str).str[8:10]
#create a new column called 'TimeSlice' that is 'M' + Month + 'D' + Day
SSP126_2040_2064_tt['TimeSlice'] = 'M' + SSP126_2040_2064_tt['Month'] + 'D' + SSP126_2040_2064_tt['Day']
# add a new column called 'Attribute' that is entirely full of 'RNW'
SSP126_2040_2064_tt['Attribute'] = 'NCAP_AF'
# add a new column called 'Yr' that is the year of the 'time' column
SSP126_2040_2064_tt['Yr'] = SSP126_2040_2064_tt['time'].astype(str).str[:4]
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_2040_2064_tt['PSET_CI'] = 'ELCWNO'


SSP126_2040_2064_tt= SSP126_2040_2064_tt.groupby(['State/Province', 'time']).first().compute()
#pivot the table so that TEMELE_REGIONS_COPY are the columns, TimeSlice are the rows, and the values are the CP
SSP126_2040_2064_tt = SSP126_2040_2064_tt.pivot_table(index=['TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI'], columns='State/Province', values='CP', aggfunc='first')
#replace all NaN values with 0
SSP126_2040_2064_tt = SSP126_2040_2064_tt.fillna(0)
# only keep TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI', 'Virginia', 'Rhode Island'
#SSP126_2040_2064_tt = SSP126_2040_2064_tt[['Virginia', 'Rhode Island']]
SSP126_2040_2064_tt

State/Province                                           Alaska   Arizona  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNO   0.315406  0.342390
          2041 01    01  2041-01-01 NCAP_AF   ELCWNO   0.000000  0.000000
          2042 01    01  2042-01-01 NCAP_AF   ELCWNO   0.000000  0.367407
          2043 01    01  2043-01-01 NCAP_AF   ELCWNO   0.193936  0.366578
          2044 01    01  2044-01-01 NCAP_AF   ELCWNO   0.193936  0.379232
...                                                         ...       ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNO   0.000000  0.337390
          2061 12    31  2061-12-31 NCAP_AF   ELCWNO   0.315406  0.328988
          2062 12    31  2062-12-31 NCAP_AF   ELCWNO   0.193936  0.000000
          2063 12    31  2063-12-31 NCAP_AF   ELCWNO   0.379232  0.337390
          2064 12    31  2064-12-31 NCAP_AF   ELCWNO   0.000000  0.000000

State/Province                                         California  Colorado  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNO     0.193936  0.349847
          2041 01    01  2041-01-01 NCAP_AF   ELCWNO     0.193936  0.433664
          2042 01    01  2042-01-01 NCAP_AF   ELCWNO     0.322068  0.448477
          2043 01    01  2043-01-01 NCAP_AF   ELCWNO     0.193936  0.429748
          2044 01    01  2044-01-01 NCAP_AF   ELCWNO     0.193936  0.419945
...                                                           ...       ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNO     0.297433  0.407135
          2061 12    31  2061-12-31 NCAP_AF   ELCWNO     0.400446  0.443265
          2062 12    31  2062-12-31 NCAP_AF   ELCWNO     0.383872  0.408077
          2063 12    31  2063-12-31 NCAP_AF   ELCWNO     0.379232  0.228435
          2064 12    31  2064-12-31 NCAP_AF   ELCWNO     0.331932  0.421035

State/Province                                           Hawaii     Idaho  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNO   0.444821  0.000000
          2041 01    01  2041-01-01 NCAP_AF   ELCWNO   0.349082  0.193936
          2042 01    01  2042-01-01 NCAP_AF   ELCWNO   0.400913  0.193936
          2043 01    01  2043-01-01 NCAP_AF   ELCWNO   0.299454  0.367848
          2044 01    01  2044-01-01 NCAP_AF   ELCWNO   0.331621  0.000000
...                                                         ...       ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNO   0.427227  0.423700
          2061 12    31  2061-12-31 NCAP_AF   ELCWNO   0.401768  0.337059
          2062 12    31  2062-12-31 NCAP_AF   ELCWNO   0.380718  0.262934
          2063 12    31  2063-12-31 NCAP_AF   ELCWNO   0.370302  0.372967
          2064 12    31  2064-12-31 NCAP_AF   ELCWNO   0.308544  0.436614

State/Province                                         Illinois   Indiana  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNO   0.245283  0.304333
          2041 01    01  2041-01-01 NCAP_AF   ELCWNO   0.424458  0.421845
          2042 01    01  2042-01-01 NCAP_AF   ELCWNO   0.452333  0.455580
          2043 01    01  2043-01-01 NCAP_AF   ELCWNO   0.375623  0.421118
          2044 01    01  2044-01-01 NCAP_AF   ELCWNO   0.409500  0.437862
...                                                         ...       ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNO   0.447269  0.450056
          2061 12    31  2061-12-31 NCAP_AF   ELCWNO   0.398536  0.304333
          2062 12    31  2062-12-31 NCAP_AF   ELCWNO   0.453615  0.455395
          2063 12    31  2063-12-31 NCAP_AF   ELCWNO   0.417445  0.409273
          2064 12    31  2064-12-31 NCAP_AF   ELCWNO   0.447934  0.452305

State/Province                                             Iowa    Kansas  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNO   0.337260  0.397304
          2041 01    01  2041-01-01 NCAP_AF   ELCWNO   0.450991  0.427296
          2042 01    01  2042-01-01 NCAP_AF   ELCWNO   0.453407  0.443616
          2043 01    01  2043-01-01 NCAP_AF   ELCWNO   0.208351  0.354240
          2044 01    01  2044-01-01 NCAP_AF   ELCWNO   0.389971  0.382232
...                                                         ...       ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNO   0.426604  0.423184
          2061 12    31  2061-12-31 NCAP_AF   ELCWNO   0.447642  0.452182
          2062 12    31  2062-12-31 NCAP_AF   ELCWNO   0.451890  0.439890
          2063 12    31  2063-12-31 NCAP_AF   ELCWNO   0.359128  0.433444
          2064 12    31  2064-12-31 NCAP_AF   ELCWNO   0.453307  0.448918

State/Province                                         ...  Pennsylvania  \
TimeSlice Yr   Month Day time       Attribute PSET_CI  ...
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNO   ...      0.343302
          2041 01    01  2041-01-01 NCAP_AF   ELCWNO   ...      0.363653
          2042 01    01  2042-01-01 NCAP_AF   ELCWNO   ...      0.415567
          2043 01    01  2043-01-01 NCAP_AF   ELCWNO   ...      0.444179
          2044 01    01  2044-01-01 NCAP_AF   ELCWNO   ...      0.431520
...                                                    ...           ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNO   ...      0.392496
          2061 12    31  2061-12-31 NCAP_AF   ELCWNO   ...      0.193936
          2062 12    31  2062-12-31 NCAP_AF   ELCWNO   ...      0.427417
          2063 12    31  2063-12-31 NCAP_AF   ELCWNO   ...      0.309258
          2064 12    31  2064-12-31 NCAP_AF   ELCWNO   ...      0.425687

State/Province                                         South Dakota  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNO       0.407807
          2041 01    01  2041-01-01 NCAP_AF   ELCWNO       0.418796
          2042 01    01  2042-01-01 NCAP_AF   ELCWNO       0.289168
          2043 01    01  2043-01-01 NCAP_AF   ELCWNO       0.306215
          2044 01    01  2044-01-01 NCAP_AF   ELCWNO       0.349136
...                                                             ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNO       0.429992
          2061 12    31  2061-12-31 NCAP_AF   ELCWNO       0.275135
          2062 12    31  2062-12-31 NCAP_AF   ELCWNO       0.432870
          2063 12    31  2063-12-31 NCAP_AF   ELCWNO       0.425110
          2064 12    31  2064-12-31 NCAP_AF   ELCWNO       0.437296

State/Province                                         Tennessee     Texas  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNO    0.331932  0.438158
          2041 01    01  2041-01-01 NCAP_AF   ELCWNO    0.000000  0.401879
          2042 01    01  2042-01-01 NCAP_AF   ELCWNO    0.193936  0.427017
          2043 01    01  2043-01-01 NCAP_AF   ELCWNO    0.193936  0.423967
          2044 01    01  2044-01-01 NCAP_AF   ELCWNO    0.193936  0.448867
...                                                          ...       ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNO    0.436877  0.405677
          2061 12    31  2061-12-31 NCAP_AF   ELCWNO    0.000000  0.406618
          2062 12    31  2062-12-31 NCAP_AF   ELCWNO    0.379232  0.435098
          2063 12    31  2063-12-31 NCAP_AF   ELCWNO    0.000000  0.424036
          2064 12    31  2064-12-31 NCAP_AF   ELCWNO    0.421845  0.431453

State/Province                                             Utah   Vermont  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNO   0.000000  0.455919
          2041 01    01  2041-01-01 NCAP_AF   ELCWNO   0.000000  0.409374
          2042 01    01  2042-01-01 NCAP_AF   ELCWNO   0.000000  0.249095
          2043 01    01  2043-01-01 NCAP_AF   ELCWNO   0.370743  0.420150
          2044 01    01  2044-01-01 NCAP_AF   ELCWNO   0.000000  0.420569
...                                                         ...       ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNO   0.414574  0.376242
          2061 12    31  2061-12-31 NCAP_AF   ELCWNO   0.424973  0.193936
          2062 12    31  2062-12-31 NCAP_AF   ELCWNO   0.379232  0.416392
          2063 12    31  2063-12-31 NCAP_AF   ELCWNO   0.000000  0.331932
          2064 12    31  2064-12-31 NCAP_AF   ELCWNO   0.193936  0.434377

State/Province                                         Washington  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNO     0.323371
          2041 01    01  2041-01-01 NCAP_AF   ELCWNO     0.288551
          2042 01    01  2042-01-01 NCAP_AF   ELCWNO     0.000000
          2043 01    01  2043-01-01 NCAP_AF   ELCWNO     0.379232
          2044 01    01  2044-01-01 NCAP_AF   ELCWNO     0.276734
...                                                           ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNO     0.439811
          2061 12    31  2061-12-31 NCAP_AF   ELCWNO     0.349023
          2062 12    31  2062-12-31 NCAP_AF   ELCWNO     0.379991
          2063 12    31  2063-12-31 NCAP_AF   ELCWNO     0.427897
          2064 12    31  2064-12-31 NCAP_AF   ELCWNO     0.358131

State/Province                                         West Virginia  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNO        0.000000
          2041 01    01  2041-01-01 NCAP_AF   ELCWNO        0.398866
          2042 01    01  2042-01-01 NCAP_AF   ELCWNO        0.416190
          2043 01    01  2043-01-01 NCAP_AF   ELCWNO        0.452128
          2044 01    01  2044-01-01 NCAP_AF   ELCWNO        0.432853
...                                                              ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNO        0.442249
          2061 12    31  2061-12-31 NCAP_AF   ELCWNO        0.000000
          2062 12    31  2062-12-31 NCAP_AF   ELCWNO        0.421146
          2063 12    31  2063-12-31 NCAP_AF   ELCWNO        0.292505
          2064 12    31  2064-12-31 NCAP_AF   ELCWNO        0.438182

State/Province                                         Wisconsin   Wyoming
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2040 01    01  2040-01-01 NCAP_AF   ELCWNO    0.262934  0.293276
          2041 01    01  2041-01-01 NCAP_AF   ELCWNO    0.424124  0.447616
          2042 01    01  2042-01-01 NCAP_AF   ELCWNO    0.444511  0.438137
          2043 01    01  2043-01-01 NCAP_AF   ELCWNO    0.397420  0.387518
          2044 01    01  2044-01-01 NCAP_AF   ELCWNO    0.433783  0.000000
...                                                          ...       ...
M12D31    2060 12    31  2060-12-31 NCAP_AF   ELCWNO    0.443161  0.447223
          2061 12    31  2061-12-31 NCAP_AF   ELCWNO    0.427858  0.413575
          2062 12    31  2062-12-31 NCAP_AF   ELCWNO    0.447530  0.437367
          2063 12    31  2063-12-31 NCAP_AF   ELCWNO    0.399969  0.444222
          2064 12    31  2064-12-31 NCAP_AF   ELCWNO    0.277124  0.417460

[9132 rows x 37 columns]

In [115]:
#export to csv
SSP126_2040_2064_tt.to_csv('SSP126_usa_onshore_2040_2064_TIMES_state.csv')

# 2065-2089

In [116]:
#   SSP 126 2065-2089
#create a new column called 'Month' that is the month of the 'time' column
SSP126_2065_2089_tt['Month'] = SSP126_2065_2089_tt['time'].astype(str).str[5:7]
#create a new column called 'Day' that is the day of the 'time' column
SSP126_2065_2089_tt['Day'] = SSP126_2065_2089_tt['time'].astype(str).str[8:10]
#create a new column called 'TimeSlice' that is 'M' + Month + 'D' + Day
SSP126_2065_2089_tt['TimeSlice'] = 'M' + SSP126_2065_2089_tt['Month'] + 'D' + SSP126_2065_2089_tt['Day']
# add a new column called 'Attribute' that is entirely full of 'RNW'
SSP126_2065_2089_tt['Attribute'] = 'NCAP_AF'
# add a new column called 'Yr' that is the year of the 'time' column
SSP126_2065_2089_tt['Yr'] = SSP126_2065_2089_tt['time'].astype(str).str[:4]
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_2065_2089_tt['PSET_CI'] = 'ELCWNO'

SSP126_2065_2089_tt= SSP126_2065_2089_tt.groupby(['State/Province', 'time']).first().compute()
#pivot the table so that TEMELE_REGIONS_COPY are the columns, TimeSlice are the rows, and the values are the CP
SSP126_2065_2089_tt = SSP126_2065_2089_tt.pivot_table(index=['TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI'], columns='State/Province', values='CP', aggfunc='first')
#replace all NaN values with 0
SSP126_2065_2089_tt = SSP126_2065_2089_tt.fillna(0)
# only keep TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI', 'Virginia', 'Rhode Island'
#SSP126_2065_2089_tt = SSP126_2065_2089_tt[['Virginia', 'Rhode Island']]
SSP126_2065_2089_tt

State/Province                                           Alaska   Arizona  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNO   0.331932  0.363378
          2066 01    01  2066-01-01 NCAP_AF   ELCWNO   0.379232  0.193936
          2067 01    01  2067-01-01 NCAP_AF   ELCWNO   0.000000  0.418542
          2068 01    01  2068-01-01 NCAP_AF   ELCWNO   0.331932  0.330590
          2069 01    01  2069-01-01 NCAP_AF   ELCWNO   0.000000  0.193936
...                                                         ...       ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNO   0.331932  0.238064
          2086 12    31  2086-12-31 NCAP_AF   ELCWNO   0.000000  0.268054
          2087 12    31  2087-12-31 NCAP_AF   ELCWNO   0.193936  0.000000
          2088 12    31  2088-12-31 NCAP_AF   ELCWNO   0.379232  0.359479
          2089 12    31  2089-12-31 NCAP_AF   ELCWNO   0.373253  0.193936

State/Province                                         California  Colorado  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNO     0.203793  0.429388
          2066 01    01  2066-01-01 NCAP_AF   ELCWNO     0.000000  0.343002
          2067 01    01  2067-01-01 NCAP_AF   ELCWNO     0.277416  0.417633
          2068 01    01  2068-01-01 NCAP_AF   ELCWNO     0.273349  0.428635
          2069 01    01  2069-01-01 NCAP_AF   ELCWNO     0.193936  0.350560
...                                                           ...       ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNO     0.329251  0.406019
          2086 12    31  2086-12-31 NCAP_AF   ELCWNO     0.309853  0.335303
          2087 12    31  2087-12-31 NCAP_AF   ELCWNO     0.203793  0.432167
          2088 12    31  2088-12-31 NCAP_AF   ELCWNO     0.268306  0.278122
          2089 12    31  2089-12-31 NCAP_AF   ELCWNO     0.228435  0.273418

State/Province                                           Hawaii     Idaho  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNO   0.391295  0.265313
          2066 01    01  2066-01-01 NCAP_AF   ELCWNO   0.263071  0.331932
          2067 01    01  2067-01-01 NCAP_AF   ELCWNO   0.243912  0.393477
          2068 01    01  2068-01-01 NCAP_AF   ELCWNO   0.355720  0.193936
          2069 01    01  2069-01-01 NCAP_AF   ELCWNO   0.335145  0.419867
...                                                         ...       ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNO   0.452825  0.326319
          2086 12    31  2086-12-31 NCAP_AF   ELCWNO   0.374249  0.379322
          2087 12    31  2087-12-31 NCAP_AF   ELCWNO   0.353785  0.000000
          2088 12    31  2088-12-31 NCAP_AF   ELCWNO   0.390744  0.397165
          2089 12    31  2089-12-31 NCAP_AF   ELCWNO   0.434557  0.193936

State/Province                                         Illinois   Indiana  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNO   0.454259  0.455634
          2066 01    01  2066-01-01 NCAP_AF   ELCWNO   0.443759  0.454348
          2067 01    01  2067-01-01 NCAP_AF   ELCWNO   0.423341  0.423761
          2068 01    01  2068-01-01 NCAP_AF   ELCWNO   0.399183  0.417846
          2069 01    01  2069-01-01 NCAP_AF   ELCWNO   0.442419  0.433958
...                                                         ...       ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNO   0.420371  0.424656
          2086 12    31  2086-12-31 NCAP_AF   ELCWNO   0.275229  0.290533
          2087 12    31  2087-12-31 NCAP_AF   ELCWNO   0.445725  0.449022
          2088 12    31  2088-12-31 NCAP_AF   ELCWNO   0.394612  0.351242
          2089 12    31  2089-12-31 NCAP_AF   ELCWNO   0.434868  0.432367

State/Province                                             Iowa    Kansas  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNO   0.449275  0.431960
          2066 01    01  2066-01-01 NCAP_AF   ELCWNO   0.444323  0.352270
          2067 01    01  2067-01-01 NCAP_AF   ELCWNO   0.440478  0.398141
          2068 01    01  2068-01-01 NCAP_AF   ELCWNO   0.422919  0.384119
          2069 01    01  2069-01-01 NCAP_AF   ELCWNO   0.445010  0.376473
...                                                         ...       ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNO   0.348916  0.395512
          2086 12    31  2086-12-31 NCAP_AF   ELCWNO   0.367026  0.320975
          2087 12    31  2087-12-31 NCAP_AF   ELCWNO   0.451786  0.427128
          2088 12    31  2088-12-31 NCAP_AF   ELCWNO   0.387423  0.277752
          2089 12    31  2089-12-31 NCAP_AF   ELCWNO   0.446680  0.397946

State/Province                                         ...  Pennsylvania  \
TimeSlice Yr   Month Day time       Attribute PSET_CI  ...
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNO   ...      0.428569
          2066 01    01  2066-01-01 NCAP_AF   ELCWNO   ...      0.386050
          2067 01    01  2067-01-01 NCAP_AF   ELCWNO   ...      0.351944
          2068 01    01  2068-01-01 NCAP_AF   ELCWNO   ...      0.420537
          2069 01    01  2069-01-01 NCAP_AF   ELCWNO   ...      0.329959
...                                                    ...           ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNO   ...      0.453794
          2086 12    31  2086-12-31 NCAP_AF   ELCWNO   ...      0.353579
          2087 12    31  2087-12-31 NCAP_AF   ELCWNO   ...      0.402686
          2088 12    31  2088-12-31 NCAP_AF   ELCWNO   ...      0.257510
          2089 12    31  2089-12-31 NCAP_AF   ELCWNO   ...      0.355547

State/Province                                         South Dakota  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNO       0.433711
          2066 01    01  2066-01-01 NCAP_AF   ELCWNO       0.443740
          2067 01    01  2067-01-01 NCAP_AF   ELCWNO       0.440861
          2068 01    01  2068-01-01 NCAP_AF   ELCWNO       0.438251
          2069 01    01  2069-01-01 NCAP_AF   ELCWNO       0.386769
...                                                             ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNO       0.432735
          2086 12    31  2086-12-31 NCAP_AF   ELCWNO       0.412487
          2087 12    31  2087-12-31 NCAP_AF   ELCWNO       0.420670
          2088 12    31  2088-12-31 NCAP_AF   ELCWNO       0.333781
          2089 12    31  2089-12-31 NCAP_AF   ELCWNO       0.448658

State/Province                                         Tennessee     Texas  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNO    0.421845  0.404221
          2066 01    01  2066-01-01 NCAP_AF   ELCWNO    0.414574  0.400924
          2067 01    01  2067-01-01 NCAP_AF   ELCWNO    0.000000  0.384131
          2068 01    01  2068-01-01 NCAP_AF   ELCWNO    0.331932  0.386234
          2069 01    01  2069-01-01 NCAP_AF   ELCWNO    0.331932  0.312794
...                                                          ...       ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNO    0.193936  0.391785
          2086 12    31  2086-12-31 NCAP_AF   ELCWNO    0.000000  0.331677
          2087 12    31  2087-12-31 NCAP_AF   ELCWNO    0.000000  0.391149
          2088 12    31  2088-12-31 NCAP_AF   ELCWNO    0.000000  0.401763
          2089 12    31  2089-12-31 NCAP_AF   ELCWNO    0.379232  0.324433

State/Province                                             Utah   Vermont  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNO   0.000000  0.193936
          2066 01    01  2066-01-01 NCAP_AF   ELCWNO   0.000000  0.309258
          2067 01    01  2067-01-01 NCAP_AF   ELCWNO   0.193936  0.331932
          2068 01    01  2068-01-01 NCAP_AF   ELCWNO   0.000000  0.425603
          2069 01    01  2069-01-01 NCAP_AF   ELCWNO   0.193936  0.343757
...                                                         ...       ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNO   0.193936  0.449221
          2086 12    31  2086-12-31 NCAP_AF   ELCWNO   0.304255  0.286584
          2087 12    31  2087-12-31 NCAP_AF   ELCWNO   0.000000  0.364418
          2088 12    31  2088-12-31 NCAP_AF   ELCWNO   0.379232  0.228435
          2089 12    31  2089-12-31 NCAP_AF   ELCWNO   0.000000  0.000000

State/Province                                         Washington  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNO     0.407404
          2066 01    01  2066-01-01 NCAP_AF   ELCWNO     0.249977
          2067 01    01  2067-01-01 NCAP_AF   ELCWNO     0.370878
          2068 01    01  2068-01-01 NCAP_AF   ELCWNO     0.373641
          2069 01    01  2069-01-01 NCAP_AF   ELCWNO     0.193936
...                                                           ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNO     0.193936
          2086 12    31  2086-12-31 NCAP_AF   ELCWNO     0.303867
          2087 12    31  2087-12-31 NCAP_AF   ELCWNO     0.331932
          2088 12    31  2088-12-31 NCAP_AF   ELCWNO     0.322040
          2089 12    31  2089-12-31 NCAP_AF   ELCWNO     0.000000

State/Province                                         West Virginia  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNO        0.437623
          2066 01    01  2066-01-01 NCAP_AF   ELCWNO        0.370278
          2067 01    01  2067-01-01 NCAP_AF   ELCWNO        0.365718
          2068 01    01  2068-01-01 NCAP_AF   ELCWNO        0.406720
          2069 01    01  2069-01-01 NCAP_AF   ELCWNO        0.273632
...                                                              ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNO        0.450649
          2086 12    31  2086-12-31 NCAP_AF   ELCWNO        0.377844
          2087 12    31  2087-12-31 NCAP_AF   ELCWNO        0.360808
          2088 12    31  2088-12-31 NCAP_AF   ELCWNO        0.000000
          2089 12    31  2089-12-31 NCAP_AF   ELCWNO        0.360808

State/Province                                         Wisconsin   Wyoming
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2065 01    01  2065-01-01 NCAP_AF   ELCWNO    0.433530  0.418929
          2066 01    01  2066-01-01 NCAP_AF   ELCWNO    0.446167  0.421965
          2067 01    01  2067-01-01 NCAP_AF   ELCWNO    0.440083  0.453035
          2068 01    01  2068-01-01 NCAP_AF   ELCWNO    0.399650  0.436825
          2069 01    01  2069-01-01 NCAP_AF   ELCWNO    0.440089  0.447308
...                                                          ...       ...
M12D31    2085 12    31  2085-12-31 NCAP_AF   ELCWNO    0.426814  0.438281
          2086 12    31  2086-12-31 NCAP_AF   ELCWNO    0.378295  0.335727
          2087 12    31  2087-12-31 NCAP_AF   ELCWNO    0.452046  0.437300
          2088 12    31  2088-12-31 NCAP_AF   ELCWNO    0.420440  0.418073
          2089 12    31  2089-12-31 NCAP_AF   ELCWNO    0.447830  0.317509

[9131 rows x 37 columns]

In [117]:
#export to csv
SSP126_2065_2089_tt.to_csv('SSP126_usa_onshore_2065_2089_TIMES_state.csv')

# 2090-2100

In [118]:
#   SSP 126 2090-2100

#create a new column called 'Month' that is the month of the 'time' column
SSP126_2090_2100_tt['Month'] = SSP126_2090_2100_tt['time'].astype(str).str[5:7]
#create a new column called 'Day' that is the day of the 'time' column
SSP126_2090_2100_tt['Day'] = SSP126_2090_2100_tt['time'].astype(str).str[8:10]
#create a new column called 'TimeSlice' that is 'M' + Month + 'D' + Day
SSP126_2090_2100_tt['TimeSlice'] = 'M' + SSP126_2090_2100_tt['Month'] + 'D' + SSP126_2090_2100_tt['Day']
# add a new column called 'Attribute' that is entirely full of 'RNW'
SSP126_2090_2100_tt['Attribute'] = 'NCAP_AF'
# add a new column called 'Yr' that is the year of the 'time' column
SSP126_2090_2100_tt['Yr'] = SSP126_2090_2100_tt['time'].astype(str).str[:4]
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_2090_2100_tt['PSET_CI'] = 'ELCWNO'


SSP126_2090_2100_tt= SSP126_2090_2100_tt.groupby(['State/Province', 'time']).first().compute()
#pivot the table so that TEMELE_REGIONS_COPY are the columns, TimeSlice are the rows, and the values are the CP
SSP126_2090_2100_tt = SSP126_2090_2100_tt.pivot_table(index=['TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI'], columns='State/Province', values='CP', aggfunc='first')
#replace all NaN values with 0
SSP126_2090_2100_tt = SSP126_2090_2100_tt.fillna(0)

# only keep TimeSlice', 'Yr', 'Month', 'Day', 'time', 'Attribute', 'PSET_CI', 'Virginia', 'Rhode Island'
#SSP126_2090_2100_tt = SSP126_2090_2100_tt[['Virginia', 'Rhode Island']]

In [119]:
SSP126_2090_2100_tt

State/Province                                           Alaska   Arizona  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO   0.373253  0.286584
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO   0.286584  0.000000
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO   0.000000  0.000000
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO   0.000000  0.409875
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO   0.286584  0.414376
...                                                         ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO   0.436877  0.000000
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO   0.436877  0.000000
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO   0.262934  0.000000
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO   0.286584  0.420715
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO   0.436877  0.000000

State/Province                                         California  Colorado  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO     0.193936  0.427342
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO     0.412891  0.430728
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO     0.204968  0.441314
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO     0.335874  0.273990
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO     0.364110  0.426356
...                                                           ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO     0.193936  0.361812
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO     0.193936  0.251434
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO     0.000000  0.368305
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO     0.343285  0.414903
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO     0.193936  0.421668

State/Province                                           Hawaii     Idaho  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO   0.387657  0.349724
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO   0.390321  0.331932
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO   0.429870  0.388481
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO   0.384936  0.193936
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO   0.377857  0.000000
...                                                         ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO   0.270562  0.322161
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO   0.388807  0.193936
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO   0.376164  0.267534
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO   0.406899  0.000000
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO   0.315110  0.397278

State/Province                                         Illinois   Indiana  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO   0.322816  0.383935
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO   0.312915  0.416128
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO   0.414582  0.428609
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO   0.193936  0.193936
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO   0.434312  0.442886
...                                                         ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO   0.453190  0.447735
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO   0.393868  0.419351
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO   0.347733  0.422721
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO   0.446841  0.451885
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO   0.452043  0.445974

State/Province                                             Iowa    Kansas  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO   0.434031  0.368223
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO   0.000000  0.329062
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO   0.439492  0.437743
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO   0.193936  0.371422
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO   0.445058  0.408021
...                                                         ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO   0.443624  0.449882
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO   0.417585  0.323056
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO   0.312037  0.246241
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO   0.391796  0.400717
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO   0.444348  0.414321

State/Province                                         ...  Pennsylvania  \
TimeSlice Yr   Month Day time       Attribute PSET_CI  ...
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO   ...      0.422476
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO   ...      0.452021
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO   ...      0.301131
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO   ...      0.210171
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO   ...      0.420977
...                                                    ...           ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO   ...      0.193936
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO   ...      0.430387
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO   ...      0.447695
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO   ...      0.429529
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO   ...      0.412388

State/Province                                         South Dakota  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO       0.439862
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO       0.193936
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO       0.454324
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO       0.331932
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO       0.444994
...                                                             ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO       0.426541
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO       0.382373
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO       0.416118
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO       0.428987
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO       0.370383

State/Province                                         Tennessee     Texas  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO    0.193936  0.405364
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO    0.193936  0.392244
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO    0.379232  0.440659
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO    0.000000  0.437227
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO    0.000000  0.380180
...                                                          ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO    0.193936  0.438664
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO    0.193936  0.376243
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO    0.000000  0.346226
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO    0.421845  0.374630
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO    0.436877  0.422045

State/Province                                             Utah   Vermont  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO   0.000000  0.343757
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO   0.000000  0.250913
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO   0.193936  0.193936
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO   0.379232  0.321083
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO   0.193936  0.398721
...                                                         ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO   0.317467  0.297433
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO   0.000000  0.274759
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO   0.331932  0.432233
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO   0.414574  0.449178
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO   0.414574  0.193936

State/Province                                         Washington  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO     0.193936
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO     0.376388
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO     0.431401
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO     0.393611
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO     0.304255
...                                                           ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO     0.332689
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO     0.275123
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO     0.410152
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO     0.193936
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO     0.373243

State/Province                                         West Virginia  \
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO        0.428580
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO        0.452602
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO        0.284144
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO        0.000000
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO        0.378190
...                                                              ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO        0.193936
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO        0.433226
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO        0.446350
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO        0.405605
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO        0.433632

State/Province                                         Wisconsin   Wyoming
TimeSlice Yr   Month Day time       Attribute PSET_CI
M01D01    2090 01    01  2090-01-01 NCAP_AF   ELCWNO    0.409278  0.435086
          2091 01    01  2091-01-01 NCAP_AF   ELCWNO    0.410667  0.444799
          2092 01    01  2092-01-01 NCAP_AF   ELCWNO    0.395238  0.440063
          2093 01    01  2093-01-01 NCAP_AF   ELCWNO    0.259834  0.405082
          2094 01    01  2094-01-01 NCAP_AF   ELCWNO    0.421751  0.402644
...                                                          ...       ...
M12D31    2096 12    31  2096-12-31 NCAP_AF   ELCWNO    0.440182  0.339113
          2097 12    31  2097-12-31 NCAP_AF   ELCWNO    0.439616  0.193936
          2098 12    31  2098-12-31 NCAP_AF   ELCWNO    0.423576  0.452690
          2099 12    31  2099-12-31 NCAP_AF   ELCWNO    0.446959  0.439477
          2100 12    31  2100-12-31 NCAP_AF   ELCWNO    0.450916  0.425620

[4017 rows x 37 columns]

In [120]:
#export to csv
SSP126_2090_2100_tt.to_csv('SSP126_usa_onshore_2090_2100_TIMES_state.csv')

# Organize into TIMES Time Slices

In [121]:
import polars as pl

# Read all the *TIMES.csv files in Polars and concatenate them
SSP126_TIMES = pl.read_csv('SSP126_usa_onshore_2015_2039_TIMES_state.csv')
SSP126_TIMES = SSP126_TIMES.extend(pl.read_csv('SSP126_usa_onshore_2040_2064_TIMES_state.csv'))
SSP126_TIMES = SSP126_TIMES.extend(pl.read_csv('SSP126_usa_onshore_2065_2089_TIMES_state.csv'))
SSP126_TIMES = SSP126_TIMES.extend(pl.read_csv('SSP126_usa_onshore_2090_2100_TIMES_state.csv'))

# Filter the DataFrame to keep only rows with 'Yr' greater than or equal to 2020
SSP126_TIMES = SSP126_TIMES.filter(pl.col('Yr') >= 2020)

In [122]:
SSP126_TIMES.head()

shape: (5, 44)
┌───────────┬──────┬───────┬─────┬───┬────────────┬───────────────┬───────────┬──────────┐
│ TimeSlice ┆ Yr   ┆ Month ┆ Day ┆ … ┆ Washington ┆ West Virginia ┆ Wisconsin ┆ Wyoming  │
│ ---       ┆ ---  ┆ ---   ┆ --- ┆   ┆ ---        ┆ ---           ┆ ---       ┆ ---      │
│ str       ┆ i64  ┆ i64   ┆ i64 ┆   ┆ f64        ┆ f64           ┆ f64       ┆ f64      │
╞═══════════╪══════╪═══════╪═════╪═══╪════════════╪═══════════════╪═══════════╪══════════╡
│ M01D01    ┆ 2020 ┆ 1     ┆ 1   ┆ … ┆ 0.411531   ┆ 0.331932      ┆ 0.425844  ┆ 0.401381 │
│ M01D01    ┆ 2021 ┆ 1     ┆ 1   ┆ … ┆ 0.193936   ┆ 0.193936      ┆ 0.4295778 ┆ 0.429521 │
│ M01D01    ┆ 2022 ┆ 1     ┆ 1   ┆ … ┆ 0.373321   ┆ 0.398171      ┆ 0.0       ┆ 0.446337 │
│ M01D01    ┆ 2023 ┆ 1     ┆ 1   ┆ … ┆ 0.413848   ┆ 0.224602      ┆ 0.379906  ┆ 0.40699  │
│ M01D01    ┆ 2024 ┆ 1     ┆ 1   ┆ … ┆ 0.392115   ┆ 0.265779      ┆ 0.4342062 ┆ 0.242139 │
└───────────┴──────┴───────┴─────┴───┴────────────┴───────────────┴───────────┴──────────┘

In [123]:
import polars as pl

# Add 'Season' column based on the 'Month' column
SSP126_TIMES = SSP126_TIMES.with_columns(
    Season=
    SSP126_TIMES["Month"].apply(
        lambda month: "S01" if month in [1, 2, 12] else "S02" if month in [3, 4, 5] else "S03" if month in [6, 7, 8] else "S04"
    ),
)

#read 'time' column as datetime 

SSP126_TIMES = SSP126_TIMES.with_columns(pl.col('time').str.strptime(pl.Datetime).alias('time'))

# find the weekday number of the 'time' column 
SSP126_TIMES = SSP126_TIMES.with_columns(
    Weekday=
    SSP126_TIMES["time"].apply(
        lambda time: time.isoweekday()
    ),
)

# if the 'Weekday' is equal to 6, 2, 3, 4, or 5, then the 'Type' is 'WD2', otherwise it is 'WD1'
SSP126_TIMES = SSP126_TIMES.with_columns(
    Type=
    SSP126_TIMES["Weekday"].apply(
        lambda Weekday: "WD2" if Weekday in [6, 2, 3, 4, 5] else "WD1"
    ),
)

SSP126_TIMES = SSP126_TIMES.with_columns(pl.lit('NCAP_AF').alias('Attribute'))

In [124]:
SSP126_TIMES

shape: (29_585, 47)
┌───────────┬──────┬───────┬─────┬───┬──────────┬────────┬─────────┬──────┐
│ TimeSlice ┆ Yr   ┆ Month ┆ Day ┆ … ┆ Wyoming  ┆ Season ┆ Weekday ┆ Type │
│ ---       ┆ ---  ┆ ---   ┆ --- ┆   ┆ ---      ┆ ---    ┆ ---     ┆ ---  │
│ str       ┆ i64  ┆ i64   ┆ i64 ┆   ┆ f64      ┆ str    ┆ i64     ┆ str  │
╞═══════════╪══════╪═══════╪═════╪═══╪══════════╪════════╪═════════╪══════╡
│ M01D01    ┆ 2020 ┆ 1     ┆ 1   ┆ … ┆ 0.401381 ┆ S01    ┆ 3       ┆ WD2  │
│ M01D01    ┆ 2021 ┆ 1     ┆ 1   ┆ … ┆ 0.429521 ┆ S01    ┆ 5       ┆ WD2  │
│ M01D01    ┆ 2022 ┆ 1     ┆ 1   ┆ … ┆ 0.446337 ┆ S01    ┆ 6       ┆ WD2  │
│ M01D01    ┆ 2023 ┆ 1     ┆ 1   ┆ … ┆ 0.40699  ┆ S01    ┆ 7       ┆ WD1  │
│ …         ┆ …    ┆ …     ┆ …   ┆ … ┆ …        ┆ …      ┆ …       ┆ …    │
│ M12D31    ┆ 2097 ┆ 12    ┆ 31  ┆ … ┆ 0.193936 ┆ S01    ┆ 2       ┆ WD2  │
│ M12D31    ┆ 2098 ┆ 12    ┆ 31  ┆ … ┆ 0.45269  ┆ S01    ┆ 3       ┆ WD2  │
│ M12D31    ┆ 2099 ┆ 12    ┆ 31  ┆ … ┆ 0.439477 ┆ S01    ┆ 4       ┆ WD2  │
│ M12D31    ┆ 2100 ┆ 12    ┆ 31  ┆ … ┆ 0.42562  ┆ S01    ┆ 5       ┆ WD2  │
└───────────┴──────┴───────┴─────┴───┴──────────┴────────┴─────────┴──────┘

# TS - 8760
Daily/hourly values. Ex: January 1, 2020 in USA

In [56]:

SSP126_TIMES.head()

shape: (5, 12)
┌───────────┬──────┬───────┬─────┬───┬──────────────┬────────┬─────────┬──────┐
│ TimeSlice ┆ Yr   ┆ Month ┆ Day ┆ … ┆ Rhode Island ┆ Season ┆ Weekday ┆ Type │
│ ---       ┆ ---  ┆ ---   ┆ --- ┆   ┆ ---          ┆ ---    ┆ ---     ┆ ---  │
│ str       ┆ i64  ┆ i64   ┆ i64 ┆   ┆ f64          ┆ str    ┆ i64     ┆ str  │
╞═══════════╪══════╪═══════╪═════╪═══╪══════════════╪════════╪═════════╪══════╡
│ M01D01    ┆ 2020 ┆ 1     ┆ 1   ┆ … ┆ 0.379232     ┆ S01    ┆ 3       ┆ WD2  │
│ M01D01    ┆ 2021 ┆ 1     ┆ 1   ┆ … ┆ 0.436877     ┆ S01    ┆ 5       ┆ WD2  │
│ M01D01    ┆ 2022 ┆ 1     ┆ 1   ┆ … ┆ 0.193936     ┆ S01    ┆ 6       ┆ WD2  │
│ M01D01    ┆ 2023 ┆ 1     ┆ 1   ┆ … ┆ 0.436877     ┆ S01    ┆ 7       ┆ WD1  │
│ M01D01    ┆ 2024 ┆ 1     ┆ 1   ┆ … ┆ 0.421845     ┆ S01    ┆ 1       ┆ WD1  │
└───────────┴──────┴───────┴─────┴───┴──────────────┴────────┴─────────┴──────┘

In [126]:
# save to csv 
SSP126_TIMES.write_csv('SSP126_Onshore_TS8760_TUSM.csv') # Onshore
#SSP126_TIMES.write_csv('SSP126_Offshore_TS8760_TUSM.csv') # Offshore

# TS - 120
Averaged by month and weekday type by country. ex: Weekdays in January in 2020 in USA, Weekends in January in 2020 in USA

In [127]:
# Group by year, month, type, then calculate the average for each groupby 
#groupby the Yr and Season and find mean 
SSP126_TIMES_120 = SSP126_TIMES.groupby(['Yr', 'Month', 'Type']).mean()
# sort by year and season
SSP126_TIMES_120 = SSP126_TIMES_120.sort(['Yr', 'Month'])
# make all rows in the 'PSET_CI' column 'ELCWNF' in polars
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_TIMES_120 = SSP126_TIMES_120.with_columns(pl.col('PSET_CI').fill_null('ELCWNF'))
# do the same but RNW for Attribute
SSP126_TIMES_120 = SSP126_TIMES_120.with_columns(pl.col('Attribute').fill_null('NCAP_AF'))
# make a column called 'M' that is just 'M' + Month
SSP126_TIMES_120 = SSP126_TIMES_120.with_columns(pl.lit('M').alias('M'))
#create a new column called 'TimeSlice' that is 'M' + Month + Type
SSP126_TIMES_120 = SSP126_TIMES_120.with_columns(pl.concat_str([pl.col('M'), pl.col('Month').cast(pl.Utf8).str.zfill(2), pl.col('Type')], separator='').alias('TimeSlice'))
# drop TimeSlice, time, Attribute, and PSET_CI columns
SSP126_TIMES_120 = SSP126_TIMES_120.drop(['Day', 'time', 'Type', 'M', 'Season', 'Weekday', 'Month'])

SSP126_TIMES_120

shape: (1_944, 41)
┌──────┬───────────┬───────────┬─────────┬───┬────────────┬───────────────┬───────────┬──────────┐
│ Yr   ┆ TimeSlice ┆ Attribute ┆ PSET_CI ┆ … ┆ Washington ┆ West Virginia ┆ Wisconsin ┆ Wyoming  │
│ ---  ┆ ---       ┆ ---       ┆ ---     ┆   ┆ ---        ┆ ---           ┆ ---       ┆ ---      │
│ i64  ┆ str       ┆ str       ┆ str     ┆   ┆ f64        ┆ f64           ┆ f64       ┆ f64      │
╞══════╪═══════════╪═══════════╪═════════╪═══╪════════════╪═══════════════╪═══════════╪══════════╡
│ 2020 ┆ M01WD2    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.240074   ┆ 0.40167       ┆ 0.415271  ┆ 0.395379 │
│ 2020 ┆ M01WD1    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.209207   ┆ 0.410489      ┆ 0.420618  ┆ 0.3909   │
│ 2020 ┆ M02WD2    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.210539   ┆ 0.380669      ┆ 0.382917  ┆ 0.404372 │
│ 2020 ┆ M02WD1    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.215463   ┆ 0.347265      ┆ 0.426494  ┆ 0.400748 │
│ …    ┆ …         ┆ …         ┆ …       ┆ … ┆ …          ┆ …             ┆ …         ┆ …        │
│ 2100 ┆ M11WD1    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.300148   ┆ 0.258501      ┆ 0.391508  ┆ 0.360802 │
│ 2100 ┆ M11WD2    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.31744    ┆ 0.277884      ┆ 0.373034  ┆ 0.408761 │
│ 2100 ┆ M12WD2    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.206978   ┆ 0.361045      ┆ 0.389008  ┆ 0.370645 │
│ 2100 ┆ M12WD1    ┆ NCAP_AF   ┆ ELCWNF  ┆ … ┆ 0.224898   ┆ 0.330853      ┆ 0.35167   ┆ 0.344594 │
└──────┴───────────┴───────────┴─────────┴───┴────────────┴───────────────┴───────────┴──────────┘

In [128]:
# save to csv 
SSP126_TIMES_120.write_csv('SSP126_Onshore_TS120_TUSM.csv') # Onshore
#SSP126_TIMES_120.write_csv('SSP126_Offshore_TS120_TUSM.csv') # Offshore

# TS - 40
Averaged by season and weekday type by country. ex: Weekdays in Fall in 2020 in USA, Weekends in Fall in 2020 in USA

In [129]:
#groupby the Yr and Season and find mean 
SSP126_TIMES_40 = SSP126_TIMES.groupby(['Yr', 'Season', 'Type']).mean()
# sort by year and season
SSP126_TIMES_40 = SSP126_TIMES_40.sort(['Yr', 'Season'])
# drop TimeSlice, time, Attribute, and PSET_CI columns
SSP126_TIMES_40 = SSP126_TIMES_40.drop(['TimeSlice', 'time', 'Weekday', 'Month', 'Day'])
# make all rows in the 'PSET_CI' column 'ELCWNF' in polars
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_TIMES_40 = SSP126_TIMES_40.with_columns(pl.col('PSET_CI').fill_null('ELCWNF'))
# do the same but RNW for Attribute
SSP126_TIMES_40 = SSP126_TIMES_40.with_columns(pl.col('Attribute').fill_null('NCAP_AF'))
#Create a column called 'TimeSlice' that is the Season + Type
SSP126_TIMES_40 = SSP126_TIMES_40.with_columns(pl.concat_str([pl.col('Season'), pl.col('Type')], separator='').alias('TimeSlice'))
# drop the Season and Type columns
SSP126_TIMES_40 = SSP126_TIMES_40.drop(['Season', 'Type'])

SSP126_TIMES_40

shape: (648, 41)
┌──────┬───────────┬─────────┬──────────┬───┬───────────────┬───────────┬──────────┬───────────┐
│ Yr   ┆ Attribute ┆ PSET_CI ┆ Alaska   ┆ … ┆ West Virginia ┆ Wisconsin ┆ Wyoming  ┆ TimeSlice │
│ ---  ┆ ---       ┆ ---     ┆ ---      ┆   ┆ ---           ┆ ---       ┆ ---      ┆ ---       │
│ i64  ┆ str       ┆ str     ┆ f64      ┆   ┆ f64           ┆ f64       ┆ f64      ┆ str       │
╞══════╪═══════════╪═════════╪══════════╪═══╪═══════════════╪═══════════╪══════════╪═══════════╡
│ 2020 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.182352 ┆ … ┆ 0.361544      ┆ 0.40742   ┆ 0.401618 ┆ S01WD1    │
│ 2020 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.236909 ┆ … ┆ 0.364334      ┆ 0.392486  ┆ 0.393919 ┆ S01WD2    │
│ 2020 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.21209  ┆ … ┆ 0.357096      ┆ 0.40407   ┆ 0.391624 ┆ S02WD1    │
│ 2020 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.168132 ┆ … ┆ 0.286876      ┆ 0.403908  ┆ 0.398014 ┆ S02WD2    │
│ …    ┆ …         ┆ …       ┆ …        ┆ … ┆ …             ┆ …         ┆ …        ┆ …         │
│ 2100 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.152556 ┆ … ┆ 0.15813       ┆ 0.28936   ┆ 0.371564 ┆ S03WD2    │
│ 2100 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.139576 ┆ … ┆ 0.097672      ┆ 0.313969  ┆ 0.329102 ┆ S03WD1    │
│ 2100 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.21855  ┆ … ┆ 0.250776      ┆ 0.386381  ┆ 0.385671 ┆ S04WD1    │
│ 2100 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.16183  ┆ … ┆ 0.281063      ┆ 0.377712  ┆ 0.394393 ┆ S04WD2    │
└──────┴───────────┴─────────┴──────────┴───┴───────────────┴───────────┴──────────┴───────────┘

In [131]:
# save to csv 
SSP126_TIMES_40.write_csv('SSP126_Onshore_TS40_TUSM.csv') # Onshore
#SSP126_TIMES_40.write_csv('SSP126_Offshore_TS40_TUSM.csv') # Offshore

# TS - 1
Averaged annually by country. ex: 2020 in USA

In [132]:

#groupby the Yr and find mean 
SSP126_TIMES_1 = SSP126_TIMES.groupby(['Yr']).mean()
# sort by year and season
SSP126_TIMES_1 = SSP126_TIMES_1.sort(['Yr'])
# drop TimeSlice, time, Attribute, and PSET_CI columns
SSP126_TIMES_1 = SSP126_TIMES_1.drop(['TimeSlice', 'time', 'Weekday', 'Month', 'Day', 'Season', 'Type'])
# make all rows in the 'PSET_CI' column 'ELCWNF' in polars
# add a new column called 'PSET_CI' that is 'ELCWNO' for onshore or 'ELCWNF' for offshore
SSP126_TIMES_1 = SSP126_TIMES_1.with_columns(pl.col('PSET_CI').fill_null('ELCWNF'))
# do the same but RNW for Attribute
SSP126_TIMES_1 = SSP126_TIMES_1.with_columns(pl.col('Attribute').fill_null('NCAP_AF'))
SSP126_TIMES_1.head()

shape: (5, 40)
┌──────┬───────────┬─────────┬──────────┬───┬────────────┬───────────────┬───────────┬──────────┐
│ Yr   ┆ Attribute ┆ PSET_CI ┆ Alaska   ┆ … ┆ Washington ┆ West Virginia ┆ Wisconsin ┆ Wyoming  │
│ ---  ┆ ---       ┆ ---     ┆ ---      ┆   ┆ ---        ┆ ---           ┆ ---       ┆ ---      │
│ i64  ┆ str       ┆ str     ┆ f64      ┆   ┆ f64        ┆ f64           ┆ f64       ┆ f64      │
╞══════╪═══════════╪═════════╪══════════╪═══╪════════════╪═══════════════╪═══════════╪══════════╡
│ 2020 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.180993 ┆ … ┆ 0.283018   ┆ 0.289865      ┆ 0.372747  ┆ 0.374808 │
│ 2021 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.204236 ┆ … ┆ 0.298011   ┆ 0.268369      ┆ 0.366676  ┆ 0.388531 │
│ 2022 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.187651 ┆ … ┆ 0.308552   ┆ 0.261587      ┆ 0.371924  ┆ 0.396001 │
│ 2023 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.194789 ┆ … ┆ 0.300427   ┆ 0.251464      ┆ 0.35675   ┆ 0.395413 │
│ 2024 ┆ NCAP_AF   ┆ ELCWNF  ┆ 0.179206 ┆ … ┆ 0.302084   ┆ 0.250924      ┆ 0.352601  ┆ 0.395021 │
└──────┴───────────┴─────────┴──────────┴───┴────────────┴───────────────┴───────────┴──────────┘

In [133]:
# save to csv 
SSP126_TIMES_1.write_csv('SSP126_Onshore_TS1_TUSM.csv') # Onshore
#SSP126_TIMES_1.write_csv('SSP126_Offshore_TS1_TUSM.csv') # Offshore